param([string]$BaseUrl='http://127.0.0.1:8788',[switch]$SelfTest)
$ErrorActionPreference='Stop'
$BaseUrl=$BaseUrl.TrimEnd('/')
if($BaseUrl-ne'http://127.0.0.1:8788'){throw 'Router VPN Windows product app only uses the fixed local controller.'}
Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase
[xml]$Xaml=@'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="Router VPN" Height="800" Width="1180" MinHeight="680" MinWidth="980" WindowStartupLocation="CenterScreen" Background="#0B1020" Foreground="#F5F7FF">
<Grid Margin="18"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
<Grid Grid.Row="0" Margin="4,0,4,14"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Router VPN" FontSize="30" FontWeight="Bold"/><TextBlock Name="HeaderDetail" Text="Native Windows product app" Foreground="#93A4C7"/></StackPanel><Border Grid.Column="1" Background="#152038" CornerRadius="16" Padding="16,8"><StackPanel Orientation="Horizontal"><Ellipse Name="StateDot" Width="10" Height="10" Fill="#6B7280" Margin="0,0,8,0"/><TextBlock Name="StateText" Text="Checking..." FontWeight="SemiBold"/></StackPanel></Border></Grid>
<TabControl Grid.Row="1" Background="#0F172A" BorderBrush="#263452" Foreground="#E8ECF8">
<TabItem Header="Home / Connect"><ScrollViewer><StackPanel Margin="12"><GroupBox Header="Connection" Margin="8" Padding="10"><StackPanel><TextBlock Text="Router"/><ComboBox Name="RouterCombo" DisplayMemberPath="name" SelectedValuePath="id" Margin="4"/><TextBlock Text="Mode" Margin="0,8,0,0"/><ComboBox Name="ModeCombo" DisplayMemberPath="name" SelectedValuePath="id" Margin="4"/><TextBlock Text="Tunnel base" Margin="0,8,0,0"/><ComboBox Name="BaseCombo" Margin="4"><ComboBoxItem Content="Auto" Tag="auto"/><ComboBoxItem Content="WireGuard" Tag="wg"/><ComboBoxItem Content="AmneziaWG" Tag="awg"/></ComboBox><WrapPanel Margin="0,12,0,0"><Button Name="AutoButton" Content="AUTO Connect" Margin="4" Padding="13,8"/><Button Name="ConnectButton" Content="Connect Selected" Margin="4" Padding="13,8"/><Button Name="DisconnectButton" Content="Disconnect" Margin="4" Padding="13,8"/><Button Name="RefreshButton" Content="Refresh" Margin="4" Padding="13,8"/></WrapPanel><TextBlock Name="ConnectionDetail" TextWrapping="Wrap" Margin="4,12,4,0" Foreground="#A8B6D5"/></StackPanel></GroupBox><GroupBox Header="Connection proof" Margin="8" Padding="10"><StackPanel><TextBlock Name="ProofText" Text="Connected requires exact selected-router private path proof." TextWrapping="Wrap"/><TextBlock Name="LastErrorText" Foreground="#FF9CA8" TextWrapping="Wrap"/></StackPanel></GroupBox></StackPanel></ScrollViewer></TabItem>
<TabItem Header="Nodes / Map"><Grid Margin="14"><Grid.RowDefinitions><RowDefinition Height="240"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Border Background="#0E182B" BorderBrush="#33415F" BorderThickness="1" CornerRadius="10"><Canvas Name="MapCanvas" ClipToBounds="True"/></Border><DataGrid Grid.Row="1" Name="NodesGrid" AutoGenerateColumns="False" IsReadOnly="True" Margin="0,10,0,0"><DataGrid.Columns><DataGridTextColumn Header="Name" Binding="{Binding name}" Width="2*"/><DataGridTextColumn Header="Location" Binding="{Binding location}" Width="*"/><DataGridTextColumn Header="Endpoint" Binding="{Binding endpoint}" Width="2*"/><DataGridTextColumn Header="Median ms" Binding="{Binding latency_median_ms}" Width="*"/></DataGrid.Columns></DataGrid><WrapPanel Grid.Row="2"><Button Name="SelectNodeButton" Content="Select highlighted node" Margin="4"/><Button Name="LatencyButton" Content="Run 50-sample latency" Margin="4"/></WrapPanel></Grid></TabItem>
<TabItem Header="Modes"><Grid Margin="14"><DataGrid Name="ModesGrid" AutoGenerateColumns="False" IsReadOnly="True"><DataGrid.Columns><DataGridTextColumn Header="Mode" Binding="{Binding name}" Width="2*"/><DataGridCheckBoxColumn Header="Available" Binding="{Binding available}" Width="90"/><DataGridTextColumn Header="Ready bases" Binding="{Binding ready_bases_text}" Width="130"/><DataGridTextColumn Header="Reason" Binding="{Binding reason}" Width="3*"/></DataGrid.Columns></DataGrid></Grid></TabItem>
<TabItem Header="DNS"><StackPanel Margin="18"><TextBlock Text="DNS" FontSize="20" FontWeight="Bold"/><TextBlock Name="DnsSummary" TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="DnsButton" Content="Retest home-exit DNS" HorizontalAlignment="Left"/><TextBlock Text="Saved DNS is not proof; session proof reports active runtime enforcement and resolver success." TextWrapping="Wrap" Margin="0,12,0,0"/></StackPanel></TabItem>
<TabItem Header="Advanced"><StackPanel Margin="18"><TextBlock Text="Advanced" FontSize="20" FontWeight="Bold"/><TextBlock Name="AdvancedSummary" TextWrapping="Wrap" Margin="0,8,0,0"/></StackPanel></TabItem>
<TabItem Header="Forwarding"><StackPanel Margin="18"><TextBlock Text="Forwarding" FontSize="20" FontWeight="Bold"/><TextBlock Text="Incoming forwarding is managed by the authenticated private Setup Center/router-agent surface. This client never exposes an admin token or fakes DNAT in proxy-only modes." TextWrapping="Wrap" Margin="0,8,0,0"/></StackPanel></TabItem>
<TabItem Header="Settings"><StackPanel Margin="18"><TextBlock Text="Settings" FontSize="20" FontWeight="Bold"/><TextBlock Name="SettingsSummary" TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="SettingsRefreshButton" Content="Refresh local state" HorizontalAlignment="Left"/></StackPanel></TabItem>
<TabItem Header="Help"><StackPanel Margin="18"><TextBlock Text="Help" FontSize="20" FontWeight="Bold"/><TextBlock Text="Install once, link node data separately, choose node/mode, connect, then prove the selected node, public exit and DNS. Unavailable modes stay unavailable until their real prerequisite is ready." TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="TutorialButton" Content="Run full native onboarding again" HorizontalAlignment="Left"/></StackPanel></TabItem>
<TabItem Header="Diagnostics"><StackPanel Margin="18"><TextBlock Text="Typed connection progress and proof" FontSize="20" FontWeight="Bold"/><WrapPanel><Button Name="PublicIpButton" Content="Prove public VPN exit" Margin="4"/><Button Name="EmergencyButton" Content="Emergency stop" Margin="4"/></WrapPanel><TextBox Name="DiagnosticsBox" Height="380" IsReadOnly="True" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"/></StackPanel></TabItem>
</TabControl><TextBlock Grid.Row="2" Margin="4,12,4,0" Foreground="#7E90B6" Text="Native WPF; fixed local controller 127.0.0.1:8788; no browser or embedded web surface."/></Grid></Window>
'@
$Reader=New-Object System.Xml.XmlNodeReader $Xaml
$Window=[Windows.Markup.XamlReader]::Load($Reader)
function Control([string]$Name){return $Window.FindName($Name)}
if($SelfTest){
 foreach($Name in @('StateText','RouterCombo','ModeCombo','MapCanvas','NodesGrid','ModesGrid','DnsSummary','AdvancedSummary','DiagnosticsBox','TutorialButton')){if(-not(Control $Name)){throw "Windows product self-test missing $Name"}}
 $Source=Get-Content -LiteralPath $MyInvocation.MyCommand.Path -Raw
 foreach($Marker in @('/api/status','/api/profiles','/api/logical-modes','/api/connect-logical','/api/session','/api/session/events','/api/emergency-stop','latitude','longitude','No real node coordinates','Forwarding','Settings','Help')){if($Source-notlike"*$Marker*"){throw "Windows product contract missing $Marker"}}
 Write-Host 'Router VPN Windows product self-test: OK'
 exit 0
}
$StateText=Control 'StateText';$StateDot=Control 'StateDot';$HeaderDetail=Control 'HeaderDetail';$RouterCombo=Control 'RouterCombo';$ModeCombo=Control 'ModeCombo';$BaseCombo=Control 'BaseCombo';$ConnectionDetail=Control 'ConnectionDetail';$ProofText=Control 'ProofText';$LastErrorText=Control 'LastErrorText';$NodesGrid=Control 'NodesGrid';$MapCanvas=Control 'MapCanvas';$ModesGrid=Control 'ModesGrid';$DnsSummary=Control 'DnsSummary';$AdvancedSummary=Control 'AdvancedSummary';$SettingsSummary=Control 'SettingsSummary';$DiagnosticsBox=Control 'DiagnosticsBox'
$script:EventSeq=[uint64]0;$script:Busy=$false
function Api{param([string]$Path,[string]$Method='GET',$Body=$null,[int]$Timeout=45);$Uri="$BaseUrl$Path";if($Method-eq'GET'){return Invoke-RestMethod -Uri $Uri -Method Get -TimeoutSec $Timeout};$Json=if($null-eq$Body){'{}'}else{$Body|ConvertTo-Json -Depth 12 -Compress};return Invoke-RestMethod -Uri $Uri -Method $Method -ContentType 'application/json' -Body $Json -TimeoutSec $Timeout}
function Log([string]$Text){$DiagnosticsBox.AppendText("[$(Get-Date -Format 'HH:mm:ss')] $Text`r`n");$DiagnosticsBox.ScrollToEnd()}
function BaseChoice{$Item=$BaseCombo.SelectedItem;if($Item-and$Item.Tag){return [string]$Item.Tag};return 'auto'}
function AddLine($x1,$y1,$x2,$y2,[string]$Color){$Line=New-Object Windows.Shapes.Line;$Line.X1=$x1;$Line.Y1=$y1;$Line.X2=$x2;$Line.Y2=$y2;$Line.Stroke=$Color;$Line.StrokeThickness=1;[void]$MapCanvas.Children.Add($Line)}
function DrawMap($Profiles,[string]$Selected){$MapCanvas.Children.Clear();$Width=[Math]::Max(640,[double]$MapCanvas.ActualWidth);$Height=[Math]::Max(200,[double]$MapCanvas.ActualHeight);foreach($Lon in @(-120,-60,0,60,120)){$X=($Lon+180)/360*$Width;AddLine $X 0 $X $Height '#2D3D57'};foreach($Lat in @(-60,-30,0,30,60)){$Y=(90-$Lat)/180*$Height;AddLine 0 $Y $Width $Y '#2D3D57'};$Count=0;foreach($Profile in @($Profiles)){try{$Lat=[Convert]::ToDouble($Profile.latitude,[Globalization.CultureInfo]::InvariantCulture);$Lon=[Convert]::ToDouble($Profile.longitude,[Globalization.CultureInfo]::InvariantCulture)}catch{continue};if($Lat-lt-90-or$Lat-gt90-or$Lon-lt-180-or$Lon-gt180-or($Lat-eq0-and$Lon-eq0)){continue};$X=($Lon+180)/360*$Width;$Y=(90-$Lat)/180*$Height;$Dot=New-Object Windows.Shapes.Ellipse;$Dot.Width=if([string]$Profile.id-eq$Selected){16}else{12};$Dot.Height=$Dot.Width;$Dot.Fill=if([string]$Profile.id-eq$Selected){'#7B68FF'}else{'#62D5FF'};[Windows.Controls.Canvas]::SetLeft($Dot,$X-$Dot.Width/2);[Windows.Controls.Canvas]::SetTop($Dot,$Y-$Dot.Height/2);$Dot.ToolTip="$($Profile.name) latitude=$Lat longitude=$Lon";[void]$MapCanvas.Children.Add($Dot);$Count++};if($Count-eq0){$Empty=New-Object Windows.Controls.TextBlock;$Empty.Text='No real node coordinates in linked profiles';$Empty.Foreground='#AEBBD5';[Windows.Controls.Canvas]::SetLeft($Empty,20);[Windows.Controls.Canvas]::SetTop($Empty,20);[void]$MapCanvas.Children.Add($Empty)}}
function SessionEvents{try{$Timeline=Api ("/api/session/events?after="+$script:EventSeq) -Timeout 3;foreach($Event in @($Timeline.events)){$Seq=[uint64]$Event.seq;if($Seq-le$script:EventSeq){continue};$Parts=@([string]$Event.phase);if($Event.runtime_mode){$Parts+=("runtime="+$Event.runtime_mode)};if($Event.base){$Parts+=("base="+$Event.base)};if($Event.message){$Parts+=$Event.message};Log ("Session #$Seq $($Event.type): $($Parts-join' | ')");$script:EventSeq=$Seq};if([uint64]$Timeline.last_event_seq-gt$script:EventSeq){$script:EventSeq=[uint64]$Timeline.last_event_seq}}catch{}}
function RefreshProduct{if($script:Busy){return};$script:Busy=$true;try{$Status=Api '/api/status' -Timeout 3;$Connected=[bool]$Status.connected;$StateText.Text=if($Connected){'Connected'}elseif($Status.phase){$Status.phase}else{'Off'};$StateDot.Fill=if($Connected){'#35D07F'}elseif($Status.phase-eq'failed'){'#FF5D6C'}else{'#6B7280'};$Runtime=if($Status.runtime_mode){$Status.runtime_mode}else{$Status.mode};$ConnectionDetail.Text="Phase: $($Status.phase) Logical: $($Status.logical_mode) Runtime: $Runtime Base: $($Status.base) Router: $($Status.router_id)";$LastErrorText.Text=[string]$Status.last_error;if($Connected){$ProofText.Text='Connected - selected-router private path proof passed.'};$Store=Api '/api/profiles' -Timeout 3;$Profiles=@($Store.profiles);$RouterCombo.ItemsSource=$Profiles;$NodesGrid.ItemsSource=$Profiles;if($Store.selected_id){$RouterCombo.SelectedValue=[string]$Store.selected_id};DrawMap $Profiles ([string]$Store.selected_id);$Selected=@($Profiles|Where-Object{[string]$_.id-eq[string]$Store.selected_id}|Select-Object -First 1);if($Selected.Count){$Profile=$Selected[0];$AdvancedSummary.Text="LAN=$($Profile.home_lan_access) Kill switch=$($Profile.kill_switch_policy) MTU=$($Profile.mtu_mode) Effective MTU=$($Profile.effective_mtu) Multihop=$($Profile.multihop_enabled)";$SettingsSummary.Text="Node=$($Profile.name) Endpoint=$($Profile.endpoint) Location=$($Profile.location)"};$Session=Api '/api/session' -Timeout 3;$Dns=$Session.dns_proof;$DnsSummary.Text="Mode=$($Dns.mode) Resolver=$($Dns.host) Proof=$($Dns.status) Latency=$($Dns.latency_ms)ms Reason=$($Dns.reason)";$Modes=@(Api '/api/logical-modes' -Timeout 12);foreach($Mode in $Modes){$Mode|Add-Member -NotePropertyName ready_bases_text -NotePropertyValue ((@($Mode.ready_bases)-join', ').ToUpperInvariant()) -Force};$ModesGrid.ItemsSource=$Modes;$ModeCombo.ItemsSource=@($Modes|Where-Object{$_.available});if(-not$ModeCombo.SelectedValue-and$ModeCombo.Items.Count-gt0){$ModeCombo.SelectedIndex=0};$HeaderDetail.Text="Native Windows product - $($Profiles.Count) linked node(s)";SessionEvents}catch{$StateText.Text='Controller unavailable';$StateDot.Fill='#FF5D6C';$LastErrorText.Text=$_.Exception.Message}finally{$script:Busy=$false}}
(Control 'RefreshButton').Add_Click({RefreshProduct});(Control 'SettingsRefreshButton').Add_Click({RefreshProduct});(Control 'AutoButton').Add_Click({try{$Result=Api '/api/auto' 'POST' @{} 120;Log ("AUTO runtime=$($Result.runtime_mode)")}catch{Log ("AUTO failed: $($_.Exception.Message)")};RefreshProduct});(Control 'ConnectButton').Add_Click({try{$Mode=[string]$ModeCombo.SelectedValue;if(-not$Mode){throw 'Choose an available mode.'};$Result=Api '/api/connect-logical' 'POST' @{mode=$Mode;base=(BaseChoice)} 150;Log ("Connected runtime=$($Result.runtime_mode) base=$($Result.base)")}catch{Log ("Connect failed: $($_.Exception.Message)")};RefreshProduct});(Control 'DisconnectButton').Add_Click({try{[void](Api '/api/disconnect' 'POST' @{} 15);Log 'Disconnected'}catch{Log $_.Exception.Message};RefreshProduct});(Control 'PublicIpButton').Add_Click({try{$Result=Api '/api/public-ip' -Timeout 12;Log ("Public VPN exit: $($Result.public_ip)")}catch{Log $_.Exception.Message}});(Control 'DnsButton').Add_Click({try{$Result=Api '/api/dns/retest' 'POST' @{} 60;Log ("DNS winner: $($Result.winner.address) $($Result.winner.latency_ms)ms")}catch{Log $_.Exception.Message};RefreshProduct});(Control 'EmergencyButton').Add_Click({try{[void](Api '/api/emergency-stop' 'POST' @{} 15);Log 'Emergency stop completed'}catch{Log $_.Exception.Message};RefreshProduct});(Control 'SelectNodeButton').Add_Click({try{$Profile=$NodesGrid.SelectedItem;if(-not$Profile){throw 'Highlight a node first.'};[void](Api '/api/profile/select' 'POST' @{id=[string]$Profile.id} 10)}catch{Log $_.Exception.Message};RefreshProduct});(Control 'LatencyButton').Add_Click({try{$Profile=$NodesGrid.SelectedItem;if(-not$Profile){throw 'Highlight a node first.'};$Result=Api '/api/profile/latency' 'POST' @{id=[string]$Profile.id;samples=50} 180;Log ("Latency median=$($Result.median_ms)ms p90=$($Result.p90_ms)ms")}catch{Log $_.Exception.Message};RefreshProduct});$RouterCombo.Add_SelectionChanged({if($RouterCombo.SelectedValue){try{[void](Api '/api/profile/select' 'POST' @{id=[string]$RouterCombo.SelectedValue} 10)}catch{};RefreshProduct}});(Control 'TutorialButton').Add_Click({[System.Windows.MessageBox]::Show('Install once; link node data separately; choose the intended node and mode; connect; watch typed progress; prove selected path, public exit and DNS; use Setup Center for server forwarding and recovery.','Router VPN native onboarding')|Out-Null})
$BaseCombo.SelectedIndex=0
$Timer=New-Object Windows.Threading.DispatcherTimer
$Timer.Interval=[TimeSpan]::FromSeconds(2)
$Timer.Add_Tick({RefreshProduct})
$Window.Add_Closed({$Timer.Stop()})
RefreshProduct
$Timer.Start()
[void]$Window.ShowDialog()
