param([string]$BaseUrl='http://127.0.0.1:8788',[switch]$SelfTest)
$ErrorActionPreference='Stop';$BaseUrl=$BaseUrl.TrimEnd('/');if($BaseUrl-ne'http://127.0.0.1:8788'){throw'Router VPN Windows product app only uses the fixed local controller.'}
Add-Type -AssemblyName PresentationFramework;Add-Type -AssemblyName PresentationCore;Add-Type -AssemblyName WindowsBase
[xml]$Xaml=@'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="Router VPN" Height="800" Width="1180" MinHeight="680" MinWidth="980" WindowStartupLocation="CenterScreen" Background="#0B1020" Foreground="#F5F7FF">
<Window.Resources><Style TargetType="Button"><Setter Property="Margin" Value="4"/><Setter Property="Padding" Value="13,8"/><Setter Property="Background" Value="#3157E3"/><Setter Property="Foreground" Value="White"/><Setter Property="BorderThickness" Value="0"/><Setter Property="FontWeight" Value="SemiBold"/></Style><Style TargetType="TextBox"><Setter Property="Margin" Value="4"/><Setter Property="Padding" Value="8"/><Setter Property="Background" Value="#161F36"/><Setter Property="Foreground" Value="White"/><Setter Property="BorderBrush" Value="#33415F"/></Style><Style TargetType="ComboBox"><Setter Property="Margin" Value="4"/><Setter Property="Padding" Value="7"/><Setter Property="Foreground" Value="Black"/></Style><Style TargetType="GroupBox"><Setter Property="Margin" Value="8"/><Setter Property="Padding" Value="10"/><Setter Property="BorderBrush" Value="#263452"/><Setter Property="Foreground" Value="#F5F7FF"/></Style></Window.Resources>
<Grid Margin="18"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
<Grid Grid.Row="0" Margin="4,0,4,14"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Router VPN" FontSize="30" FontWeight="Bold"/><TextBlock Name="HeaderDetail" Text="Native Windows product app" Foreground="#93A4C7"/></StackPanel><Border Grid.Column="1" Background="#152038" CornerRadius="16" Padding="16,8"><StackPanel Orientation="Horizontal"><Ellipse Name="StateDot" Width="10" Height="10" Fill="#6B7280" Margin="0,0,8,0"/><TextBlock Name="StateText" Text="Checking..." FontWeight="SemiBold"/></StackPanel></Border></Grid>
<TabControl Grid.Row="1" Background="#0F172A" BorderBrush="#263452" Foreground="#E8ECF8">
<TabItem Header="Home / Connect"><ScrollViewer><StackPanel Margin="12"><GroupBox Header="Connection"><StackPanel><TextBlock Text="Router"/><ComboBox Name="RouterCombo" DisplayMemberPath="name" SelectedValuePath="id"/><TextBlock Text="Mode" Margin="0,8,0,0"/><ComboBox Name="ModeCombo" DisplayMemberPath="name" SelectedValuePath="id"/><TextBlock Text="Tunnel base" Margin="0,8,0,0"/><ComboBox Name="BaseCombo"><ComboBoxItem Content="Auto" Tag="auto"/><ComboBoxItem Content="WireGuard" Tag="wg"/><ComboBoxItem Content="AmneziaWG" Tag="awg"/></ComboBox><WrapPanel Margin="0,12,0,0"><Button Name="AutoButton" Content="AUTO Connect"/><Button Name="ConnectButton" Content="Connect Selected"/><Button Name="DisconnectButton" Content="Disconnect" Background="#B83248"/><Button Name="RefreshButton" Content="Refresh" Background="#33415F"/></WrapPanel><TextBlock Name="ConnectionDetail" TextWrapping="Wrap" Margin="4,12,4,0" Foreground="#A8B6D5"/></StackPanel></GroupBox><GroupBox Header="Connection proof"><StackPanel><TextBlock Name="ProofText" Text="Connected requires exact selected-router private path proof." TextWrapping="Wrap"/><TextBlock Name="LastErrorText" Foreground="#FF9CA8" TextWrapping="Wrap"/></StackPanel></GroupBox></StackPanel></ScrollViewer></TabItem>
<TabItem Header="Nodes / Map"><Grid Margin="14"><Grid.RowDefinitions><RowDefinition Height="240"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Border Background="#0E182B" BorderBrush="#33415F" BorderThickness="1" CornerRadius="10"><Canvas Name="MapCanvas" ClipToBounds="True"/></Border><DataGrid Grid.Row="1" Name="NodesGrid" AutoGenerateColumns="False" IsReadOnly="True" Background="#111A2E" Foreground="White" Margin="0,10,0,0"><DataGrid.Columns><DataGridTextColumn Header="Name" Binding="{Binding name}" Width="2*"/><DataGridTextColumn Header="Location" Binding="{Binding location}" Width="*"/><DataGridTextColumn Header="Endpoint" Binding="{Binding endpoint}" Width="2*"/><DataGridTextColumn Header="Median ms" Binding="{Binding latency_median_ms}" Width="*"/></DataGrid.Columns></DataGrid><WrapPanel Grid.Row="2"><Button Name="SelectNodeButton" Content="Select highlighted node"/><Button Name="LatencyButton" Content="Run 50-sample latency" Background="#33415F"/></WrapPanel></Grid></TabItem>
<TabItem Header="Modes"><Grid Margin="14"><DataGrid Name="ModesGrid" AutoGenerateColumns="False" IsReadOnly="True" Background="#111A2E" Foreground="White"><DataGrid.Columns><DataGridTextColumn Header="Mode" Binding="{Binding name}" Width="2*"/><DataGridCheckBoxColumn Header="Available" Binding="{Binding available}" Width="90"/><DataGridTextColumn Header="Ready bases" Binding="{Binding ready_bases_text}" Width="130"/><DataGridTextColumn Header="Reason" Binding="{Binding reason}" Width="3*"/></DataGrid.Columns></DataGrid></Grid></TabItem>
<TabItem Header="DNS"><StackPanel Margin="18"><TextBlock Text="DNS" FontSize="20" FontWeight="Bold"/><TextBlock Name="DnsSummary" TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="DnsButton" Content="Retest home-exit DNS" HorizontalAlignment="Left"/><TextBlock Text="Saved DNS is not proof; session proof reports active runtime enforcement and resolver success." TextWrapping="Wrap" Margin="0,12,0,0"/></StackPanel></TabItem>
<TabItem Header="Advanced"><StackPanel Margin="18"><TextBlock Text="Advanced" FontSize="20" FontWeight="Bold"/><TextBlock Name="AdvancedSummary" TextWrapping="Wrap" Margin="0,8,0,0"/></StackPanel></TabItem>
<TabItem Header="Forwarding"><StackPanel Margin="18"><TextBlock Text="Forwarding" FontSize="20" FontWeight="Bold"/><TextBlock Text="Incoming forwarding is managed by the authenticated private Setup Center/router-agent surface. This client never exposes an admin token or fakes DNAT in proxy-only modes." TextWrapping="Wrap" Margin="0,8,0,0"/></StackPanel></TabItem>
<TabItem Header="Settings"><StackPanel Margin="18"><TextBlock Text="Settings" FontSize="20" FontWeight="Bold"/><TextBlock Name="SettingsSummary" TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="SettingsRefreshButton" Content="Refresh local state" HorizontalAlignment="Left"/></StackPanel></TabItem>
<TabItem Header="Help"><StackPanel Margin="18"><TextBlock Text="Help" FontSize="20" FontWeight="Bold"/><TextBlock Text="Install once, link node data separately, choose node/mode, connect, then prove the selected node, public exit and DNS. Unavailable modes stay unavailable until their real prerequisite is ready." TextWrapping="Wrap" Margin="0,8,0,12"/><Button Name="TutorialButton" Content="Run full native onboarding again" HorizontalAlignment="Left"/></StackPanel></TabItem>
<TabItem Header="Diagnostics"><StackPanel Margin="18"><TextBlock Text="Typed connection progress and proof" FontSize="20" FontWeight="Bold"/><WrapPanel><Button Name="PublicIpButton" Content="Prove public VPN exit"/><Button Name="EmergencyButton" Content="Emergency stop" Background="#B83248"/></WrapPanel><TextBox Name="DiagnosticsBox" Height="380" IsReadOnly="True" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"/></StackPanel></TabItem>
</TabControl><TextBlock Grid.Row="2" Margin="4,12,4,0" Foreground="#7E90B6" Text="Native WPF; fixed local controller 127.0.0.1:8788; no browser or embedded web surface."/></Grid></Window>
'@
$Reader=New-Object System.Xml.XmlNodeReader $Xaml;$Window=[Windows.Markup.XamlReader]::Load($Reader)
if($SelfTest){foreach($n in @('StateText','RouterCombo','ModeCombo','MapCanvas','NodesGrid','ModesGrid','DnsSummary','AdvancedSummary','DiagnosticsBox','TutorialButton')){if(-not$Window.FindName($n)){throw"Windows product self-test missing $n"}};$src=Get-Content -LiteralPath $MyInvocation.MyCommand.Path -Raw;foreach($m in @('/api/status','/api/profiles','/api/logical-modes','/api/connect-logical','/api/session','/api/session/events','/api/emergency-stop','latitude','longitude','No real node coordinates','Forwarding','Settings','Help')){if($src-notlike"*$m*"){throw"Windows product contract missing $m"}};Write-Host'Router VPN Windows product self-test: OK';exit 0}
function C([string]$n){$Window.FindName($n)};$StateText=C'StateText';$StateDot=C'StateDot';$HeaderDetail=C'HeaderDetail';$RouterCombo=C'RouterCombo';$ModeCombo=C'ModeCombo';$BaseCombo=C'BaseCombo';$ConnectionDetail=C'ConnectionDetail';$ProofText=C'ProofText';$LastErrorText=C'LastErrorText';$NodesGrid=C'NodesGrid';$MapCanvas=C'MapCanvas';$ModesGrid=C'ModesGrid';$DnsSummary=C'DnsSummary';$AdvancedSummary=C'AdvancedSummary';$SettingsSummary=C'SettingsSummary';$DiagnosticsBox=C'DiagnosticsBox';$script:EventSeq=[uint64]0;$script:Busy=$false
function Api{param([string]$Path,[string]$Method='GET',$Body=$null,[int]$Timeout=45);$u="$BaseUrl$Path";if($Method-eq'GET'){return Invoke-RestMethod -Uri $u -Method Get -TimeoutSec $Timeout};$j=if($null-eq$Body){'{}'}else{$Body|ConvertTo-Json -Depth 12 -Compress};Invoke-RestMethod -Uri $u -Method $Method -ContentType'application/json' -Body $j -TimeoutSec $Timeout}
function Log([string]$t){$DiagnosticsBox.AppendText("[$(Get-Date -Format 'HH:mm:ss')] $t`r`n");$DiagnosticsBox.ScrollToEnd()}
function BaseChoice{$i=$BaseCombo.SelectedItem;if($i-and$i.Tag){[string]$i.Tag}else{'auto'}}
function Line($x1,$y1,$x2,$y2,$color){$l=New-Object Windows.Shapes.Line;$l.X1=$x1;$l.Y1=$y1;$l.X2=$x2;$l.Y2=$y2;$l.Stroke=$color;$l.StrokeThickness=1;[void]$MapCanvas.Children.Add($l)}
function DrawMap($Profiles,[string]$Selected){$MapCanvas.Children.Clear();$w=[Math]::Max(640,[double]$MapCanvas.ActualWidth);$h=[Math]::Max(200,[double]$MapCanvas.ActualHeight);foreach($lon in @(-120,-60,0,60,120)){$x=($lon+180)/360*$w;Line $x 0 $x $h '#2D3D57'};foreach($lat in @(-60,-30,0,30,60)){$y=(90-$lat)/180*$h;Line 0 $y $w $y '#2D3D57'};$count=0;foreach($p in @($Profiles)){try{$lat=[Convert]::ToDouble($p.latitude,[Globalization.CultureInfo]::InvariantCulture);$lon=[Convert]::ToDouble($p.longitude,[Globalization.CultureInfo]::InvariantCulture)}catch{continue};if($lat-lt-90-or$lat-gt90-or$lon-lt-180-or$lon-gt180-or($lat-eq0-and$lon-eq0)){continue};$x=($lon+180)/360*$w;$y=(90-$lat)/180*$h;$e=New-Object Windows.Shapes.Ellipse;$e.Width=if([string]$p.id-eq$Selected){16}else{12};$e.Height=$e.Width;$e.Fill=if([string]$p.id-eq$Selected){'#7B68FF'}else{'#62D5FF'};[Windows.Controls.Canvas]::SetLeft($e,$x-$e.Width/2);[Windows.Controls.Canvas]::SetTop($e,$y-$e.Height/2);$e.ToolTip="$($p.name) latitude=$lat longitude=$lon";[void]$MapCanvas.Children.Add($e);$count++};if($count-eq0){$t=New-Object Windows.Controls.TextBlock;$t.Text='No real node coordinates in linked profiles';$t.Foreground='#AEBBD5';[Windows.Controls.Canvas]::SetLeft($t,20);[Windows.Controls.Canvas]::SetTop($t,20);[void]$MapCanvas.Children.Add($t)}}
function Events{try{$r=Api("/api/session/events?after="+$script:EventSeq)-Timeout 3;foreach($e in @($r.events)){$s=[uint64]$e.seq;if($s-le$script:EventSeq){continue};$parts=@([string]$e.phase);if($e.runtime_mode){$parts+=("runtime="+$e.runtime_mode)};if($e.base){$parts+=("base="+$e.base)};if($e.message){$parts+=$e.message};Log("Session #$s $($e.type): $($parts-join' | ')");$script:EventSeq=$s};if([uint64]$r.last_event_seq-gt$script:EventSeq){$script:EventSeq=[uint64]$r.last_event_seq}}catch{}}
function Refresh{if($script:Busy){return};$script:Busy=$true;try{$s=Api'/api/status'-Timeout 3;$on=[bool]$s.connected;$StateText.Text=if($on){'Connected'}elseif($s.phase){$s.phase}else{'Off'};$StateDot.Fill=if($on){'#35D07F'}elseif($s.phase-eq'failed'){'#FF5D6C'}else{'#6B7280'};$runtime=if($s.runtime_mode){$s.runtime_mode}else{$s.mode};$ConnectionDetail.Text="Phase: $($s.phase) Logical: $($s.logical_mode) Runtime: $runtime Base: $($s.base) Router: $($s.router_id)";$LastErrorText.Text=[string]$s.last_error;if($on){$ProofText.Text='Connected - selected-router private path proof passed.'};$ps=Api'/api/profiles'-Timeout 3;$items=@($ps.profiles);$RouterCombo.ItemsSource=$items;$NodesGrid.ItemsSource=$items;if($ps.selected_id){$RouterCombo.SelectedValue=[string]$ps.selected_id};DrawMap $items ([string]$ps.selected_id);$sel=@($items|Where-Object{[string]$_.id-eq[string]$ps.selected_id}|Select-Object -First 1);if($sel.Count){$p=$sel[0];$AdvancedSummary.Text="LAN=$($p.home_lan_access) Kill switch=$($p.kill_switch_policy) MTU=$($p.mtu_mode) Effective MTU=$($p.effective_mtu) Multihop=$($p.multihop_enabled)";$SettingsSummary.Text="Node=$($p.name) Endpoint=$($p.endpoint) Location=$($p.location)"};$session=Api'/api/session'-Timeout 3;$d=$session.dns_proof;$DnsSummary.Text="Mode=$($d.mode) Resolver=$($d.host) Proof=$($d.status) Latency=$($d.latency_ms)ms Reason=$($d.reason)";$m=@(Api'/api/logical-modes'-Timeout 12);foreach($x in $m){$x|Add-Member ready_bases_text ((@($x.ready_bases)-join', ').ToUpperInvariant()) -Force};$ModesGrid.ItemsSource=$m;$ModeCombo.ItemsSource=@($m|Where-Object{$_.available});if(-not$ModeCombo.SelectedValue-and$ModeCombo.Items.Count-gt0){$ModeCombo.SelectedIndex=0};$HeaderDetail.Text="Native Windows product - $($items.Count) linked node(s)";Events}catch{$StateText.Text='Controller unavailable';$StateDot.Fill='#FF5D6C';$LastErrorText.Text=$_.Exception.Message}finally{$script:Busy=$false}}
(C'RefreshButton').Add_Click({Refresh});(C'SettingsRefreshButton').Add_Click({Refresh});(C'AutoButton').Add_Click({try{$r=Api'/api/auto''POST'@{}120;Log("AUTO runtime=$($r.runtime_mode)")}catch{Log("AUTO failed: $($_.Exception.Message)")};Refresh});(C'ConnectButton').Add_Click({try{$mode=[string]$ModeCombo.SelectedValue;if(-not$mode){throw'Choose an available mode.'};$r=Api'/api/connect-logical''POST'@{mode=$mode;base=(BaseChoice)}150;Log("Connected runtime=$($r.runtime_mode) base=$($r.base)")}catch{Log("Connect failed: $($_.Exception.Message)")};Refresh});(C'DisconnectButton').Add_Click({try{[void](Api'/api/disconnect''POST'@{}15);Log'Disconnected'}catch{Log($_.Exception.Message)};Refresh});(C'PublicIpButton').Add_Click({try{$r=Api'/api/public-ip'-Timeout 12;Log("Public VPN exit: $($r.public_ip)")}catch{Log($_.Exception.Message)}});(C'DnsButton').Add_Click({try{$r=Api'/api/dns/retest''POST'@{}60;Log("DNS winner: $($r.winner.address) $($r.winner.latency_ms)ms")}catch{Log($_.Exception.Message)};Refresh});(C'EmergencyButton').Add_Click({try{[void](Api'/api/emergency-stop''POST'@{}15);Log'Emergency stop completed'}catch{Log($_.Exception.Message)};Refresh});(C'SelectNodeButton').Add_Click({try{$p=$NodesGrid.SelectedItem;if(-not$p){throw'Highlight a node first.'};[void](Api'/api/profile/select''POST'@{id=[string]$p.id}10)}catch{Log($_.Exception.Message)};Refresh});(C'LatencyButton').Add_Click({try{$p=$NodesGrid.SelectedItem;if(-not$p){throw'Highlight a node first.'};$r=Api'/api/profile/latency''POST'@{id=[string]$p.id;samples=50}180;Log("Latency median=$($r.median_ms)ms p90=$($r.p90_ms)ms")}catch{Log($_.Exception.Message)};Refresh});$RouterCombo.Add_SelectionChanged({if($RouterCombo.SelectedValue){try{[void](Api'/api/profile/select''POST'@{id=[string]$RouterCombo.SelectedValue}10)}catch{};Refresh}});(C'TutorialButton').Add_Click({[System.Windows.MessageBox]::Show('Install once; link node data separately; choose the intended node and mode; connect; watch typed progress; prove selected path, public exit and DNS; use Setup Center for server forwarding and recovery.','Router VPN native onboarding')|Out-Null})
$BaseCombo.SelectedIndex=0;$timer=New-Object Windows.Threading.DispatcherTimer;$timer.Interval=[TimeSpan]::FromSeconds(2);$timer.Add_Tick({Refresh});$Window.Add_Closed({$timer.Stop()});Refresh;$timer.Start();[void]$Window.ShowDialog()
