package com.eabusham.routervpn;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public final class MainActivity extends Activity {
    private static final int IMPORT_BUNDLE = 1001;
    private static final String BUNDLE_FILE = "router-vpn-bundle.json";
    private static final String PREFS = "router-vpn";
    private static final String ONBOARDING_DONE = "onboarding_done_v2";
    private static final String ONBOARDING_STEP = "onboarding_step_v2";
    private static final int ONBOARDING_LAST_STEP = 9;

    private TextView statusView;
    private TextView endpointView;
    private TextView socksView;
    private TextView modesView;
    private String socksAddress = "";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(buildUi());
        loadSavedBundle();
        if (!prefs().getBoolean(ONBOARDING_DONE, false)) {
            showOnboarding(false);
        }
    }

    private View buildUi() {
        int pad = dp(20);
        LinearLayout content = new LinearLayout(this);
        content.setOrientation(LinearLayout.VERTICAL);
        content.setPadding(pad, pad, pad, pad);

        content.addView(text("Router VPN", 28, true));

        statusView = text(
            "Import the private router-vpn-bundle.json generated by your home router.",
            16,
            false
        );
        content.addView(statusView, margins(0, dp(12), 0, dp(12)));

        Button importButton = button("Import router bundle");
        importButton.setOnClickListener(v -> openBundlePicker());
        content.addView(importButton);

        Button copyButton = button("Copy SOCKS5 IP:port");
        copyButton.setOnClickListener(v -> copySocks());
        content.addView(copyButton, margins(0, dp(8), 0, 0));

        Button settingsButton = button("Open Android VPN settings");
        settingsButton.setOnClickListener(v -> startActivity(new Intent(Settings.ACTION_VPN_SETTINGS)));
        content.addView(settingsButton, margins(0, dp(8), 0, 0));

        Button checksButton = button("Run setup check");
        checksButton.setOnClickListener(v -> showSetupCheck());
        content.addView(checksButton, margins(0, dp(8), 0, 0));

        Button onboardingButton = button("Run full onboarding again");
        onboardingButton.setOnClickListener(v -> showOnboarding(true));
        content.addView(onboardingButton, margins(0, dp(8), 0, 0));

        endpointView = section("Endpoint", "Not imported");
        content.addView(endpointView, margins(0, dp(20), 0, 0));

        socksView = section("SOCKS5", "Not imported");
        content.addView(socksView, margins(0, dp(12), 0, 0));

        modesView = section("Modes in bundle", "Not imported");
        content.addView(modesView, margins(0, dp(12), 0, 0));

        TextView limitation = section(
            "Android tunnel status",
            "This APK is a private bundle importer/controller. The native Android VpnService " +
            "adapter for WireGuard, AmneziaWG, Xray, and sing-box is not linked yet, so this build " +
            "does not claim to provide full-device tunneling. Plain SOCKS5 works only after another " +
            "VPN/tunnel reaches the home router; never forward TCP 1080 from WAN."
        );
        content.addView(limitation, margins(0, dp(20), 0, dp(20)));

        ScrollView scroll = new ScrollView(this);
        scroll.addView(content);
        return scroll;
    }

    private SharedPreferences prefs() {
        return getSharedPreferences(PREFS, MODE_PRIVATE);
    }

    private void showOnboarding(boolean restart) {
        if (restart) {
            prefs().edit().putBoolean(ONBOARDING_DONE, false).putInt(ONBOARDING_STEP, 0).apply();
        }
        int step = Math.max(0, Math.min(ONBOARDING_LAST_STEP, prefs().getInt(ONBOARDING_STEP, 0)));
        showOnboardingStep(step);
    }

    private void showOnboardingStep(final int step) {
        AlertDialog.Builder builder = new AlertDialog.Builder(this)
            .setTitle("Router VPN setup — " + (step + 1) + "/" + (ONBOARDING_LAST_STEP + 1))
            .setMessage(onboardingText(step))
            .setNegativeButton("Close for now", (dialog, which) -> dialog.dismiss());

        if (step > 0) {
            String neutral = step == 4 ? "Import bundle" : step == 8 ? "Run setup check" : "Back";
            builder.setNeutralButton(neutral, null);
        }

        builder.setPositiveButton(step == ONBOARDING_LAST_STEP ? "Finish" : "Next", null);
        AlertDialog dialog = builder.create();
        dialog.setOnShowListener(ignored -> {
            dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v -> {
                if (step == ONBOARDING_LAST_STEP) {
                    prefs().edit().putBoolean(ONBOARDING_DONE, true).putInt(ONBOARDING_STEP, 0).apply();
                    dialog.dismiss();
                    Toast.makeText(this, "Onboarding complete", Toast.LENGTH_SHORT).show();
                } else {
                    int next = step + 1;
                    prefs().edit().putInt(ONBOARDING_STEP, next).apply();
                    dialog.dismiss();
                    showOnboardingStep(next);
                }
            });
            if (step > 0) {
                dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v -> {
                    if (step == 4) {
                        dialog.dismiss();
                        openBundlePicker();
                    } else if (step == 8) {
                        showSetupCheck();
                    } else {
                        int previous = step - 1;
                        prefs().edit().putInt(ONBOARDING_STEP, previous).apply();
                        dialog.dismiss();
                        showOnboardingStep(previous);
                    }
                });
            }
        });
        dialog.show();
    }

    private String onboardingText(int step) {
        switch (step) {
            case 0:
                return "Complete path: home node → ASUS WAN rules → client → DNS/modes → optional tests. Progress is saved. Closing does not mark it complete; Finish does.";
            case 1:
                return "Deploy the home node in Portainer: Stacks → Add stack → Repository. Compose path: server/portainer-current.yaml. Normal environment values: WAN_INTERFACE=eth0, LAN_CIDR=192.168.50.0/24, ADGUARD4=192.168.50.133. ENDPOINT is optional and can stay blank for auto-detection.";
            case 2:
                return "Verify the home node before WAN exposure. router-vpn-init and router-vpn-finalize should exit code 0; do not restart those one-shots. Long-running Router VPN services should be running. Optional host check: sudo bash server/scripts/doctor-current.sh.";
            case 3:
                return "On the home LAN download http://192.168.50.133:8786/router-vpn-client-bundle.zip and keep it private. The bundle includes router-vpn-bundle.json plus router/asus-merlin-router-vpn-forwards.sh.";
            case 4:
                return "ASUS Merlin WAN forwarding: use the bundled helper over SSH. It installs persistent JFFS hooks without replacing existing nat-start/firewall-start content. External TCP 80 maps to AI Board TCP 18080; 443/TCP, 585/UDP, 8388/TCP+UDP, 8443/UDP, 10443/11443/12443 TCP, 13443 TCP+UDP, and 51820/51822 UDP map 1:1. Never expose 1080, 8786, 8787, 9443, SSH, Portainer, or AdGuard admin. TCP 8443 ASUS management does not conflict with UDP 8443.";
            case 5:
                return "Import router-vpn-bundle.json. It carries the runtime endpoint, generated profiles, token, AdGuard/SOCKS5 details, and mode catalog. Multiple runtime router profiles are supported; nothing is hardcoded into this app.";
            case 6:
                return "Connection choices: AUTO / SMART AUTO / CUSTOM plus manual modes and ALL. DNS choices in the full client: fastest real DNS query RTT measured at the home exit, Home AdGuard, custom UDP/TCP, DoT, DoH, DoH3, and DNS Rescue. AUTO stops at the first healthy mode. SMART AUTO takes longer and preserves/restores a last-good stack. CUSTOM chooses the lightest validated compatible stack containing every required layer.";
            case 7:
                return "DAITA-like is bounded bidirectional cover traffic, not exact Mullvad DAITA/Maybenot. Jumbo TUN is only for compatible paths. SOCKS5 is ordinary IP + port with no authentication and stays LAN/tunnel-only. Incoming forwarding/Protected DMZ requires a WireGuard/AmneziaWG peer path; proxy-only modes are outbound.";
            case 8:
                return "Optional checks: use Run setup check here; on the AI Board run server/scripts/doctor-current.sh; on the ASUS router run /jffs/scripts/router-vpn-forward.sh status. Live WireGuard/AWG/REALITY/QUIC success only counts after an actual client connection/handshake. Generic UDP port checkers do not prove a VPN handshake.";
            default:
                return "Setup is complete. Finish keeps onboarding dismissed on this device. Run full onboarding again remains available on the main screen and does not erase the saved/imported router bundle. This Android build remains honest: native all-mode VpnService adapters are not linked yet, so it does not fake a live all-mode VPN connection.";
        }
    }

    private void showSetupCheck() {
        new AlertDialog.Builder(this)
            .setTitle("Router VPN setup check")
            .setMessage(setupCheckText())
            .setPositiveButton("OK", null)
            .show();
    }

    private String setupCheckText() {
        StringBuilder result = new StringBuilder();
        try (FileInputStream input = openFileInput(BUNDLE_FILE)) {
            byte[] bytes = readLimited(input, 32 * 1024 * 1024);
            JSONObject bundle = new JSONObject(new String(bytes, StandardCharsets.UTF_8));
            validateBundle(bundle);
            String endpoint = bundle.optString("endpoint", "").trim();
            String socksHost = bundle.optString("socks5Host", "").trim();
            int socksPort = bundle.optInt("socks5Port", 1080);
            JSONArray modes = bundle.optJSONArray("modes");
            result.append("✓ Router bundle imported\n");
            result.append(endpoint.isEmpty() ? "! Public endpoint is blank\n" : "✓ Public endpoint configured\n");
            result.append(!socksHost.isEmpty() && socksPort > 0 ? "✓ SOCKS5 IP + port configured\n" : "✗ SOCKS5 settings incomplete\n");
            boolean hasAll = hasMode(modes, "all");
            boolean hasSmart = hasMode(modes, "smart-auto");
            boolean hasCustom = hasMode(modes, "custom");
            result.append(hasAll && hasSmart && hasCustom ? "✓ ALL / SMART AUTO / CUSTOM present\n" : "✗ Required utility modes missing\n");
            result.append(modes != null && modes.length() >= 22 ? "✓ Full mode catalog present\n" : "! Mode catalog is incomplete\n");
        } catch (Exception error) {
            result.append("✗ Import router-vpn-bundle.json first\n");
        }
        result.append("ℹ Server test: server/scripts/doctor-current.sh\n");
        result.append("ℹ ASUS test: /jffs/scripts/router-vpn-forward.sh status\n");
        result.append("ℹ Live tunnel handshakes require a native tunnel adapter; this safe check does not claim one occurred.");
        return result.toString();
    }

    private boolean hasMode(JSONArray modes, String id) {
        if (modes == null) return false;
        for (int i = 0; i < modes.length(); i++) {
            JSONObject mode = modes.optJSONObject(i);
            if (mode != null && id.equals(mode.optString("id", ""))) return true;
        }
        return false;
    }

    private void openBundlePicker() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("application/json");
        startActivityForResult(intent, IMPORT_BUNDLE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode != IMPORT_BUNDLE || resultCode != RESULT_OK || data == null) {
            return;
        }
        Uri uri = data.getData();
        if (uri == null) {
            return;
        }
        try (InputStream input = getContentResolver().openInputStream(uri)) {
            if (input == null) {
                throw new IllegalStateException("Unable to open selected file");
            }
            byte[] bytes = readLimited(input, 32 * 1024 * 1024);
            JSONObject bundle = new JSONObject(new String(bytes, StandardCharsets.UTF_8));
            validateBundle(bundle);
            try (FileOutputStream output = openFileOutput(BUNDLE_FILE, MODE_PRIVATE)) {
                output.write(bytes);
            }
            renderBundle(bundle);
            Toast.makeText(this, "Router bundle imported", Toast.LENGTH_SHORT).show();
            if (!prefs().getBoolean(ONBOARDING_DONE, false)) {
                showOnboarding(false);
            }
        } catch (Exception error) {
            statusView.setText("Import failed: " + error.getMessage());
        }
    }

    private void loadSavedBundle() {
        try (FileInputStream input = openFileInput(BUNDLE_FILE)) {
            byte[] bytes = readLimited(input, 32 * 1024 * 1024);
            renderBundle(new JSONObject(new String(bytes, StandardCharsets.UTF_8)));
        } catch (Exception ignored) {
            statusView.setText("No private router bundle imported yet.");
        }
    }

    private void validateBundle(JSONObject bundle) {
        if (!bundle.has("profiles") || !bundle.has("modes")) {
            throw new IllegalArgumentException("This is not a Router VPN client bundle");
        }
    }

    private void renderBundle(JSONObject bundle) {
        String endpoint = bundle.optString("endpoint", "").trim();
        String socksHost = bundle.optString("socks5Host", "10.77.0.1").trim();
        int socksPort = bundle.optInt("socks5Port", 1080);
        socksAddress = socksHost + ":" + socksPort;

        endpointView.setText("Endpoint\n" + (endpoint.isEmpty() ? "Choose in a signed/native client" : endpoint));
        socksView.setText("SOCKS5\n" + socksAddress + "\nAuthentication: none (tunnel/LAN only)");

        JSONArray modes = bundle.optJSONArray("modes");
        StringBuilder names = new StringBuilder();
        if (modes != null) {
            for (int i = 0; i < modes.length(); i++) {
                JSONObject mode = modes.optJSONObject(i);
                if (mode == null) {
                    continue;
                }
                if (names.length() > 0) {
                    names.append('\n');
                }
                names.append(mode.optString("name", mode.optString("id", "unknown")));
            }
        }
        modesView.setText("Modes in bundle\n" + (names.length() == 0 ? "None" : names));
        statusView.setText("Private bundle stored in Android app-private storage.");
    }

    private void copySocks() {
        if (socksAddress.isEmpty()) {
            Toast.makeText(this, "Import the router bundle first", Toast.LENGTH_SHORT).show();
            return;
        }
        ClipboardManager clipboard = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
        clipboard.setPrimaryClip(ClipData.newPlainText("Router VPN SOCKS5", socksAddress));
        Toast.makeText(this, "Copied " + socksAddress, Toast.LENGTH_SHORT).show();
    }

    private static byte[] readLimited(InputStream input, int maxBytes) throws Exception {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[8192];
        int total = 0;
        int read;
        while ((read = input.read(buffer)) != -1) {
            total += read;
            if (total > maxBytes) {
                throw new IllegalArgumentException("Bundle is larger than 32 MB");
            }
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private TextView text(String value, int sp, boolean bold) {
        TextView view = new TextView(this);
        view.setText(value);
        view.setTextSize(sp);
        if (bold) {
            view.setTypeface(view.getTypeface(), android.graphics.Typeface.BOLD);
        }
        return view;
    }

    private TextView section(String heading, String value) {
        TextView view = text(heading + "\n" + value, 16, false);
        view.setPadding(dp(14), dp(14), dp(14), dp(14));
        view.setBackgroundColor(0xffeeeeee);
        return view;
    }

    private Button button(String label) {
        Button button = new Button(this);
        button.setText(label);
        button.setAllCaps(false);
        button.setGravity(Gravity.CENTER);
        return button;
    }

    private LinearLayout.LayoutParams margins(int left, int top, int right, int bottom) {
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT
        );
        params.setMargins(left, top, right, bottom);
        return params;
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }
}
