package com.eabusham.routervpn;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public final class MainActivity extends Activity {
    private static final int IMPORT_BUNDLE = 1001;
    private static final String BUNDLE_FILE = "router-vpn-bundle.json";

    private TextView statusView;
    private TextView endpointView;
    private TextView socksView;
    private TextView modesView;
    private String socksAddress = "";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(buildUi());
        loadSavedBundle();
    }

    private View buildUi() {
        int pad = dp(20);
        LinearLayout content = new LinearLayout(this);
        content.setOrientation(LinearLayout.VERTICAL);
        content.setPadding(pad, pad, pad, pad);

        TextView title = text("Router VPN", 28, true);
        content.addView(title);

        statusView = text(
            "Import the private router-vpn-bundle.json generated by your home router.",
            16,
            false
        );
        content.addView(statusView, margins(0, dp(12), 0, dp(12)));

        Button importButton = button("Import router bundle");
        importButton.setOnClickListener(v -> openBundlePicker());
        content.addView(importButton);

        Button copyButton = button("Copy SOCKS5 IP:port");
        copyButton.setOnClickListener(v -> copySocks());
        content.addView(copyButton, margins(0, dp(8), 0, 0));

        Button settingsButton = button("Open Android VPN settings");
        settingsButton.setOnClickListener(v -> startActivity(new Intent(Settings.ACTION_VPN_SETTINGS)));
        content.addView(settingsButton, margins(0, dp(8), 0, 0));

        endpointView = section("Endpoint", "Not imported");
        content.addView(endpointView, margins(0, dp(20), 0, 0));

        socksView = section("SOCKS5", "Not imported");
        content.addView(socksView, margins(0, dp(12), 0, 0));

        modesView = section("Modes in bundle", "Not imported");
        content.addView(modesView, margins(0, dp(12), 0, 0));

        TextView limitation = section(
            "Android tunnel status",
            "This APK is a private bundle importer/controller. The native Android VpnService " +
            "adapter for WireGuard, AmneziaWG, Xray, and sing-box is not linked yet, so this build " +
            "does not claim to provide full-device tunneling. Plain SOCKS5 works only after another " +
            "VPN/tunnel reaches the home router; never forward TCP 1080 from WAN."
        );
        content.addView(limitation, margins(0, dp(20), 0, dp(20)));

        ScrollView scroll = new ScrollView(this);
        scroll.addView(content);
        return scroll;
    }

    private void openBundlePicker() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("application/json");
        startActivityForResult(intent, IMPORT_BUNDLE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode != IMPORT_BUNDLE || resultCode != RESULT_OK || data == null) {
            return;
        }
        Uri uri = data.getData();
        if (uri == null) {
            return;
        }
        try (InputStream input = getContentResolver().openInputStream(uri)) {
            if (input == null) {
                throw new IllegalStateException("Unable to open selected file");
            }
            byte[] bytes = readLimited(input, 32 * 1024 * 1024);
            JSONObject bundle = new JSONObject(new String(bytes, StandardCharsets.UTF_8));
            validateBundle(bundle);
            try (FileOutputStream output = openFileOutput(BUNDLE_FILE, MODE_PRIVATE)) {
                output.write(bytes);
            }
            renderBundle(bundle);
            Toast.makeText(this, "Router bundle imported", Toast.LENGTH_SHORT).show();
        } catch (Exception error) {
            statusView.setText("Import failed: " + error.getMessage());
        }
    }

    private void loadSavedBundle() {
        try (FileInputStream input = openFileInput(BUNDLE_FILE)) {
            byte[] bytes = readLimited(input, 32 * 1024 * 1024);
            renderBundle(new JSONObject(new String(bytes, StandardCharsets.UTF_8)));
        } catch (Exception ignored) {
            statusView.setText("No private router bundle imported yet.");
        }
    }

    private void validateBundle(JSONObject bundle) {
        if (!bundle.has("profiles") || !bundle.has("modes")) {
            throw new IllegalArgumentException("This is not a Router VPN client bundle");
        }
    }

    private void renderBundle(JSONObject bundle) {
        String endpoint = bundle.optString("endpoint", "").trim();
        String socksHost = bundle.optString("socks5Host", "10.77.0.1").trim();
        int socksPort = bundle.optInt("socks5Port", 1080);
        socksAddress = socksHost + ":" + socksPort;

        endpointView.setText("Endpoint\n" + (endpoint.isEmpty() ? "Choose in a signed/native client" : endpoint));
        socksView.setText("SOCKS5\n" + socksAddress + "\nAuthentication: none (tunnel/LAN only)");

        JSONArray modes = bundle.optJSONArray("modes");
        StringBuilder names = new StringBuilder();
        if (modes != null) {
            for (int i = 0; i < modes.length(); i++) {
                JSONObject mode = modes.optJSONObject(i);
                if (mode == null) {
                    continue;
                }
                if (names.length() > 0) {
                    names.append('\n');
                }
                names.append(mode.optString("name", mode.optString("id", "unknown")));
            }
        }
        modesView.setText("Modes in bundle\n" + (names.length() == 0 ? "None" : names));
        statusView.setText("Private bundle stored in Android app-private storage.");
    }

    private void copySocks() {
        if (socksAddress.isEmpty()) {
            Toast.makeText(this, "Import the router bundle first", Toast.LENGTH_SHORT).show();
            return;
        }
        ClipboardManager clipboard = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
        clipboard.setPrimaryClip(ClipData.newPlainText("Router VPN SOCKS5", socksAddress));
        Toast.makeText(this, "Copied " + socksAddress, Toast.LENGTH_SHORT).show();
    }

    private static byte[] readLimited(InputStream input, int maxBytes) throws Exception {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[8192];
        int total = 0;
        int read;
        while ((read = input.read(buffer)) != -1) {
            total += read;
            if (total > maxBytes) {
                throw new IllegalArgumentException("Bundle is larger than 32 MB");
            }
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private TextView text(String value, int sp, boolean bold) {
        TextView view = new TextView(this);
        view.setText(value);
        view.setTextSize(sp);
        if (bold) {
            view.setTypeface(view.getTypeface(), android.graphics.Typeface.BOLD);
        }
        return view;
    }

    private TextView section(String heading, String value) {
        TextView view = text(heading + "\n" + value, 16, false);
        view.setPadding(dp(14), dp(14), dp(14), dp(14));
        view.setBackgroundColor(0xffeeeeee);
        return view;
    }

    private Button button(String label) {
        Button button = new Button(this);
        button.setText(label);
        button.setAllCaps(false);
        button.setGravity(Gravity.CENTER);
        return button;
    }

    private LinearLayout.LayoutParams margins(int left, int top, int right, int bottom) {
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT
        );
        params.setMargins(left, top, right, bottom);
        return params;
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }
}
