package com.eabusham.routervpn;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.net.VpnService;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.wireguard.android.backend.Tunnel;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

public final class MainActivity extends Activity {
    private static final int IMPORT_BUNDLE=1001, PREPARE_NATIVE_WG=1002, PREPARE_NATIVE_AWG=1003, PREPARE_LAYERED=1004, PREPARE_AUTO=1005;
    private static final String BUNDLE_FILE="router-vpn-bundle.json", PREFS="router-vpn", ONBOARDING_DONE="onboarding_done_v5", ONBOARDING_STEP="onboarding_step_v5";
    private static final int ONBOARDING_LAST_STEP=10;
    private TextView statusView,endpointView,socksView,modesView,nativeStatusView;
    private Button nativeConnectButton,nativeDisconnectButton,awgConnectButton,awgDisconnectButton,layeredConnectButton,layeredDisconnectButton,autoButton,smartButton,customButton;
    private String socksAddress="";
    private NativeWireGuardController wireGuard; private NativeAmneziaWGController amneziaWG; private NativeSingBoxController singBox; private AndroidModeOrchestrator orchestrator;
    private NativeSingBoxController.ModeInfo pendingLayeredMode; private boolean wgBusy,awgBusy,layeredBusy,automationBusy,pendingSmart; private List<String> pendingCustomLayers;
    private final Handler handler=new Handler(Looper.getMainLooper());

    @Override protected void onCreate(Bundle state){super.onCreate(state);wireGuard=new NativeWireGuardController(this);amneziaWG=new NativeAmneziaWGController(this);singBox=new NativeSingBoxController(this);orchestrator=new AndroidModeOrchestrator(this,wireGuard,amneziaWG,singBox);setContentView(buildUi());loadSavedBundle();refreshNativeState();if(!prefs().getBoolean(ONBOARDING_DONE,false))showOnboarding(false);}
    @Override protected void onResume(){super.onResume();refreshNativeState();}
    @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);if(orchestrator!=null)orchestrator.close();if(wireGuard!=null)wireGuard.close();if(amneziaWG!=null)amneziaWG.close();super.onDestroy();}

    private View buildUi(){int pad=dp(20);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(pad,pad,pad,pad);c.addView(text("Router VPN",28,true));statusView=text("Import or pair a private Router VPN node.",16,false);c.addView(statusView,margins(0,dp(12),0,dp(12)));
        Button importButton=button("Import router bundle");importButton.setOnClickListener(v->openBundlePicker());c.addView(importButton);
        nativeConnectButton=button("Connect native WireGuard");nativeConnectButton.setOnClickListener(v->requestNativeWireGuard());c.addView(nativeConnectButton,margins(0,dp(8),0,0));nativeDisconnectButton=button("Disconnect native WireGuard");nativeDisconnectButton.setOnClickListener(v->disconnectNativeWireGuard());c.addView(nativeDisconnectButton,margins(0,dp(8),0,0));
        awgConnectButton=button("Connect native AmneziaWG 2");awgConnectButton.setOnClickListener(v->requestNativeAmneziaWG());c.addView(awgConnectButton,margins(0,dp(8),0,0));awgDisconnectButton=button("Disconnect native AmneziaWG 2");awgDisconnectButton.setOnClickListener(v->disconnectNativeAmneziaWG());c.addView(awgDisconnectButton,margins(0,dp(8),0,0));
        layeredConnectButton=button("Connect embedded layered mode");layeredConnectButton.setOnClickListener(v->chooseLayeredMode());c.addView(layeredConnectButton,margins(0,dp(8),0,0));layeredDisconnectButton=button("Disconnect embedded layered mode");layeredDisconnectButton.setOnClickListener(v->disconnectLayered());c.addView(layeredDisconnectButton,margins(0,dp(8),0,0));
        autoButton=button("AUTO — first proven working mode");autoButton.setOnClickListener(v->requestAutomation(false,null));c.addView(autoButton,margins(0,dp(12),0,0));smartButton=button("SMART AUTO — simplify and restore safely");smartButton.setOnClickListener(v->requestAutomation(true,null));c.addView(smartButton,margins(0,dp(8),0,0));customButton=button("CUSTOM — choose required layers");customButton.setOnClickListener(v->chooseCustomLayers());c.addView(customButton,margins(0,dp(8),0,0));
        Button copy=button("Copy SOCKS5 IP:port");copy.setOnClickListener(v->copySocks());c.addView(copy,margins(0,dp(8),0,0));Button settings=button("Open Android VPN settings");settings.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_VPN_SETTINGS)));c.addView(settings,margins(0,dp(8),0,0));Button checks=button("Run setup check");checks.setOnClickListener(v->showSetupCheck());c.addView(checks,margins(0,dp(8),0,0));Button onboarding=button("Run full onboarding again");onboarding.setOnClickListener(v->showOnboarding(true));c.addView(onboarding,margins(0,dp(8),0,0));
        endpointView=section("Endpoint","Not imported");c.addView(endpointView,margins(0,dp(20),0,0));socksView=section("SOCKS5","Not imported");c.addView(socksView,margins(0,dp(12),0,0));nativeStatusView=section("Native Android VPN","Native engine states: checking");c.addView(nativeStatusView,margins(0,dp(12),0,0));modesView=section("Modes in bundle","Not imported");c.addView(modesView,margins(0,dp(12),0,0));
        c.addView(section("Android capability boundary","Raw WireGuard and AmneziaWG 2 use official embedded userspace backends. Self-contained generated sing-box profiles use pinned libbox through Android VpnService. AUTO/SMART/CUSTOM only consider candidates with real Android engines and require selected-node path proof. Mixed profiles that still require local Xray/other processes stay unavailable. Strict always-on kill-switch policy, multihop, unsupported multi-engine ALL/MAX branches and full reconnect policy remain gated until their Android adapters pass end-to-end tests. SOCKS5 stays tunnel/LAN-only; never expose TCP 1080 to WAN."),margins(0,dp(20),0,dp(20)));ScrollView s=new ScrollView(this);s.addView(c);return s;}

    private SharedPreferences prefs(){return getSharedPreferences(PREFS,MODE_PRIVATE);}private void showOnboarding(boolean restart){if(restart)prefs().edit().putBoolean(ONBOARDING_DONE,false).putInt(ONBOARDING_STEP,0).apply();showOnboardingStep(Math.max(0,Math.min(ONBOARDING_LAST_STEP,prefs().getInt(ONBOARDING_STEP,0))));}
    private void showOnboardingStep(final int step){AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle("Router VPN setup — "+(step+1)+"/"+(ONBOARDING_LAST_STEP+1)).setMessage(onboardingText(step)).setNegativeButton("Close for now",(d,w)->d.dismiss());if(step>0)b.setNeutralButton(step==5?"Import bundle":step==9?"Run setup check":"Back",null);b.setPositiveButton(step==ONBOARDING_LAST_STEP?"Finish":"Next",null);AlertDialog d=b.create();d.setOnShowListener(x->{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(step==ONBOARDING_LAST_STEP){prefs().edit().putBoolean(ONBOARDING_DONE,true).putInt(ONBOARDING_STEP,0).apply();d.dismiss();Toast.makeText(this,"Onboarding complete",Toast.LENGTH_SHORT).show();}else{int n=step+1;prefs().edit().putInt(ONBOARDING_STEP,n).apply();d.dismiss();showOnboardingStep(n);}});if(step>0)d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{if(step==5){d.dismiss();openBundlePicker();}else if(step==9)showSetupCheck();else{int p=step-1;prefs().edit().putInt(ONBOARDING_STEP,p).apply();d.dismiss();showOnboardingStep(p);}});});d.show();}
    private String onboardingText(int s){switch(s){case 0:return"Complete path: home node → authenticated Setup Center → node import/pairing → choose native/direct/AUTO/SMART/CUSTOM → Android VPN consent → selected-node proof. Progress is saved; only Finish marks completion.";case 1:return"Deploy the home node with server/portainer-current.yaml. Production services remain exact-image/SHA pinned; normal deployment never silently compiles from source.";case 2:return"Verify init/finalize and long-running services are healthy before WAN exposure. Optional AI Board check: sudo bash server/scripts/doctor-current.sh.";case 3:return"On the home LAN open http://AI_BOARD_IP:8786/. Setup Center is authenticated because it can expose private node material. Keep the permanent credential router-local; pairing codes are short-lived.";case 4:return"ASUS forwarding exposes only intended public VPN/auxiliary ports. Never expose SOCKS5 1080, Setup Center 8786, health/admin/Portainer/AdGuard/SSH or private credentials to WAN.";case 5:return"Import router-vpn-bundle.json. The app keeps it in Android app-private storage; the permanent Setup Center credential is not stored in the generic package.";case 6:return"Raw WG/AWG and self-contained libbox modes are real native choices. AUTO tests native candidates in catalog order; SMART then tries simpler candidates and restores the last proven mode if reduction fails.";case 7:return"CUSTOM lets you request layers and selects only a native candidate containing them. Android VPN consent happens before private layered session staging.";case 8:return"A TUN UP state alone is not AUTO success. Automatic choices must also reach the selected node's private health endpoint. Selected DNS is patched from the selected router profile before libbox validation.";case 9:return"Run setup check, server doctor, and ASUS forwarding status. Final release still requires live exit-IP/DNS/leak/reconnect/kill-switch checks on real devices.";default:return"Finish dismisses onboarding; reopen it any time. Unsupported mixed-engine/multihop/strict-kill-switch branches remain visibly gated rather than faked.";}}

    private void showSetupCheck(){new AlertDialog.Builder(this).setTitle("Router VPN setup check").setMessage(setupCheckText()).setPositiveButton("OK",null).show();}
    private String setupCheckText(){StringBuilder r=new StringBuilder();try(FileInputStream in=openFileInput(BUNDLE_FILE)){JSONObject b=new JSONObject(new String(readLimited(in,32*1024*1024),StandardCharsets.UTF_8));validateBundle(b);String e=b.optString("endpoint","").trim(),h=b.optString("socks5Host","").trim();int p=b.optInt("socks5Port",1080);JSONArray m=b.optJSONArray("modes");r.append("✓ Router bundle imported\n").append(e.isEmpty()?"! Public endpoint is blank\n":"✓ Public endpoint configured\n").append(!h.isEmpty()&&p>0?"✓ SOCKS5 IP + port configured\n":"✗ SOCKS5 settings incomplete\n").append(hasRawWireGuard(b)?"✓ Raw WireGuard profile available\n":"! Raw WireGuard profile missing\n").append(hasRawAmneziaWG(b)?"✓ Raw AmneziaWG 2 profile available\n":"! Raw AmneziaWG 2 profile missing\n");List<NativeSingBoxController.ModeInfo>d=singBox.listDirectLibboxModes(getFileStreamPath(BUNDLE_FILE));r.append(!d.isEmpty()?"✓ "+d.size()+" direct embedded libbox mode(s) available\n":"! No self-contained libbox profile available\n");boolean utilities=hasMode(m,"all")&&hasMode(m,"smart-auto")&&hasMode(m,"custom");r.append(utilities?"✓ Bundle catalogs ALL / SMART AUTO / CUSTOM\n":"! Utility mode catalog incomplete\n");}catch(Exception x){r.append("✗ Import/link a Router VPN node first: ").append(x.getMessage()).append('\n');}Tunnel.State w=wireGuard==null?Tunnel.State.DOWN:wireGuard.getState();org.amnezia.awg.backend.Tunnel.State a=amneziaWG==null?org.amnezia.awg.backend.Tunnel.State.DOWN:amneziaWG.getState();String ls=singBox==null?"DOWN":singBox.getState(),lm=singBox==null?"":singBox.getMode(),le=singBox==null?"":singBox.getError();r.append("ℹ WireGuard: ").append(w).append("\nℹ AmneziaWG: ").append(a).append("\nℹ Layered: ").append(ls).append(lm.isEmpty()?"":" ("+lm+")").append('\n');if(!le.isEmpty())r.append("! Last layered error: ").append(le).append('\n');r.append("ℹ AUTO/SMART/CUSTOM require selected-node path proof, not only VPN UP.\nℹ Server: server/scripts/doctor-current.sh\nℹ ASUS: /jffs/scripts/router-vpn-forward.sh status");return r.toString();}
    private boolean hasRawWireGuard(JSONObject b){JSONObject p=b.optJSONObject("profiles"),w=p==null?null:p.optJSONObject("wg");return w!=null&&!w.optString("wg.conf","").trim().isEmpty();}private boolean hasRawAmneziaWG(JSONObject b){JSONObject p=b.optJSONObject("profiles");if(p==null)return false;JSONObject a=p.optJSONObject("awg2-fast");if(a==null)a=p.optJSONObject("awg2-strong");return a!=null&&!a.optString("awg.conf","").trim().isEmpty();}private boolean hasMode(JSONArray a,String id){if(a==null)return false;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m!=null&&id.equals(m.optString("id","")))return true;}return false;}

    private boolean layeredActiveOrBusy(){String s=singBox==null?"DOWN":singBox.getState();return layeredBusy||automationBusy||"STARTING".equals(s)||"UP".equals(s)||"STOPPING".equals(s);}private boolean rawActiveOrBusy(){return wgBusy||awgBusy||automationBusy||wireGuard.getState()==Tunnel.State.UP||amneziaWG.getState()==org.amnezia.awg.backend.Tunnel.State.UP;}
    private void requestNativeWireGuard(){if(layeredActiveOrBusy()){toast("Disconnect/finish the current automatic or layered VPN first");return;}if(awgBusy||amneziaWG.getState()==org.amnezia.awg.backend.Tunnel.State.UP){toast("Disconnect AmneziaWG before starting WireGuard");return;}if(!bundleReady())return;Intent p=VpnService.prepare(this);if(p!=null){statusView.setText("Waiting for Android VPN permission…");startActivityForResult(p,PREPARE_NATIVE_WG);}else connectNativeWireGuard();}
    private void requestNativeAmneziaWG(){if(layeredActiveOrBusy()){toast("Disconnect/finish the current automatic or layered VPN first");return;}if(wgBusy||wireGuard.getState()==Tunnel.State.UP){toast("Disconnect WireGuard before starting AmneziaWG");return;}if(!bundleReady())return;Intent p=VpnService.prepare(this);if(p!=null){statusView.setText("Waiting for Android VPN permission…");startActivityForResult(p,PREPARE_NATIVE_AWG);}else connectNativeAmneziaWG();}
    private void connectNativeWireGuard(){setWgBusy(true,"WireGuard connecting…");wireGuard.connect(getFileStreamPath(BUNDLE_FILE),(s,m,e)->runOnUiThread(()->{setWgBusy(false,"WireGuard: "+s);statusView.setText(e==null&&s==Tunnel.State.UP?"Native Android WireGuard connected.":m);if(e!=null)toast(m);refreshNativeState();}));}private void connectNativeAmneziaWG(){setAwgBusy(true,"AmneziaWG connecting…");amneziaWG.connect(getFileStreamPath(BUNDLE_FILE),(s,m,e)->runOnUiThread(()->{setAwgBusy(false,"AmneziaWG: "+s);statusView.setText(e==null&&s==org.amnezia.awg.backend.Tunnel.State.UP?"Native Android AmneziaWG 2 connected.":m);if(e!=null)toast(m);refreshNativeState();}));}
    private void disconnectNativeWireGuard(){setWgBusy(true,"WireGuard disconnecting…");wireGuard.disconnect((s,m,e)->runOnUiThread(()->{setWgBusy(false,"WireGuard: "+s);statusView.setText(m);if(e!=null)toast(m);refreshNativeState();}));}private void disconnectNativeAmneziaWG(){setAwgBusy(true,"AmneziaWG disconnecting…");amneziaWG.disconnect((s,m,e)->runOnUiThread(()->{setAwgBusy(false,"AmneziaWG: "+s);statusView.setText(m);if(e!=null)toast(m);refreshNativeState();}));}

    private void chooseLayeredMode(){if(rawActiveOrBusy()){toast("Disconnect WireGuard/AmneziaWG or finish AUTO first");return;}if(layeredActiveOrBusy()){toast("Disconnect the current layered mode first");return;}if(!bundleReady())return;try{List<NativeSingBoxController.ModeInfo>m=singBox.listDirectLibboxModes(getFileStreamPath(BUNDLE_FILE));if(m.isEmpty()){new AlertDialog.Builder(this).setTitle("No direct embedded layered mode").setMessage("No self-contained sing-box full-device profile is available. Mixed local-engine profiles remain gated.").setPositiveButton("OK",null).show();return;}CharSequence[]l=new CharSequence[m.size()];for(int i=0;i<m.size();i++)l[i]=m.get(i).name+" ["+m.get(i).id+"]";new AlertDialog.Builder(this).setTitle("Choose embedded layered mode").setItems(l,(d,w)->requestLayered(m.get(w))).setNegativeButton("Cancel",null).show();}catch(Exception e){statusView.setText("Layered mode scan failed: "+e.getMessage());toast(e.getMessage());}}
    private void requestLayered(NativeSingBoxController.ModeInfo m){if(rawActiveOrBusy()||layeredActiveOrBusy()){refreshNativeState();return;}pendingLayeredMode=m;Intent p=VpnService.prepare(this);if(p!=null){statusView.setText("Waiting for Android VPN permission for "+m.name+"…");startActivityForResult(p,PREPARE_LAYERED);}else startPendingLayered();}
    private void startPendingLayered(){NativeSingBoxController.ModeInfo m=pendingLayeredMode;pendingLayeredMode=null;if(m==null)return;if(rawActiveOrBusy()||layeredActiveOrBusy()){statusView.setText("Another native VPN became active; layered start cancelled.");refreshNativeState();return;}try{NativeSingBoxController.SessionInfo s=singBox.prepareSession(getFileStreamPath(BUNDLE_FILE),m.id);layeredBusy=true;statusView.setText("Starting embedded "+m.name+"…");singBox.start(s);scheduleLayeredRefresh();}catch(Exception e){layeredBusy=false;statusView.setText("Layered start failed: "+e.getMessage());toast(e.getMessage());refreshNativeState();}}
    private void disconnectLayered(){if(singBox==null)return;layeredBusy=true;statusView.setText("Stopping embedded layered VPN…");singBox.stop();scheduleLayeredRefresh();}private void scheduleLayeredRefresh(){long[]d={250,750,1500,3000};for(long x:d)handler.postDelayed(()->{refreshNativeState();String s=singBox.getState();if(!"STARTING".equals(s)&&!"STOPPING".equals(s))layeredBusy=false;},x);}

    private void requestAutomation(boolean smart,List<String>custom){if(rawActiveOrBusy()||layeredActiveOrBusy()){toast("Disconnect the current VPN before AUTO/SMART/CUSTOM");return;}if(!bundleReady())return;pendingSmart=smart;pendingCustomLayers=custom==null?null:new ArrayList<>(custom);Intent p=VpnService.prepare(this);if(p!=null){statusView.setText("Waiting for Android VPN permission for "+(custom!=null?"CUSTOM":smart?"SMART AUTO":"AUTO")+"…");startActivityForResult(p,PREPARE_AUTO);}else startPendingAutomation();}
    private void startPendingAutomation(){final boolean smart=pendingSmart;final List<String>custom=pendingCustomLayers;pendingSmart=false;pendingCustomLayers=null;automationBusy=true;refreshNativeState();AndroidModeOrchestrator.Callback cb=new AndroidModeOrchestrator.Callback(){public void progress(String m){runOnUiThread(()->{statusView.setText(m);refreshNativeState();});}public void finished(boolean ok,String id,String m){runOnUiThread(()->{automationBusy=false;statusView.setText(m);if(!ok)toast(m);refreshNativeState();});}};if(custom!=null)orchestrator.custom(getFileStreamPath(BUNDLE_FILE),custom,cb);else orchestrator.auto(getFileStreamPath(BUNDLE_FILE),smart,cb);}
    private void chooseCustomLayers(){if(!bundleReady())return;try{List<String>layers=allCatalogLayers();if(layers.isEmpty()){toast("No mode layers are present in the imported bundle");return;}CharSequence[]labels=layers.toArray(new CharSequence[0]);boolean[]checked=new boolean[labels.length];new AlertDialog.Builder(this).setTitle("CUSTOM required layers").setMultiChoiceItems(labels,checked,(d,w,on)->checked[w]=on).setPositiveButton("Connect",(d,w)->{List<String>selected=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])selected.add(layers.get(i));if(selected.isEmpty()){toast("CUSTOM requires at least one layer");return;}requestAutomation(false,selected);}).setNegativeButton("Cancel",null).show();}catch(Exception e){toast("CUSTOM catalog failed: "+e.getMessage());}}
    private List<String>allCatalogLayers()throws Exception{JSONObject b=readBundle();JSONArray modes=b.optJSONArray("modes");Set<String>s=new LinkedHashSet<>();if(modes!=null)for(int i=0;i<modes.length();i++){JSONObject m=modes.optJSONObject(i);JSONArray l=m==null?null:m.optJSONArray("layers");if(l!=null)for(int j=0;j<l.length();j++){String v=l.optString(j,"").trim().toLowerCase();if(!v.isEmpty())s.add(v);}}return new ArrayList<>(s);}

    private void refreshNativeState(){if(nativeStatusView==null||wireGuard==null||amneziaWG==null||singBox==null)return;Tunnel.State w=wireGuard.getState();org.amnezia.awg.backend.Tunnel.State a=amneziaWG.getState();String ls=singBox.getState(),lm=singBox.getMode(),le=singBox.getError();if(!"STARTING".equals(ls)&&!"STOPPING".equals(ls))layeredBusy=false;nativeStatusView.setText("Native Android VPN\nWireGuard: "+w+"\nAmneziaWG 2: "+a+"\nLayered: "+ls+(lm.isEmpty()?"":" — "+lm)+(le.isEmpty()?"":"\nLast layered error: "+le)+(automationBusy?"\nAUTO/SMART/CUSTOM: testing…":""));boolean rawBlocked=layeredActiveOrBusy(),layeredBlocked=rawActiveOrBusy();nativeDisconnectButton.setEnabled(!automationBusy&&!wgBusy&&w==Tunnel.State.UP);awgDisconnectButton.setEnabled(!automationBusy&&!awgBusy&&a==org.amnezia.awg.backend.Tunnel.State.UP);nativeConnectButton.setEnabled(!wgBusy&&!awgBusy&&!rawBlocked&&a!=org.amnezia.awg.backend.Tunnel.State.UP);awgConnectButton.setEnabled(!wgBusy&&!awgBusy&&!rawBlocked&&w!=Tunnel.State.UP);layeredConnectButton.setEnabled(!layeredBusy&&!layeredBlocked&&!"UP".equals(ls)&&!"STARTING".equals(ls)&&!"STOPPING".equals(ls));layeredDisconnectButton.setEnabled(!automationBusy&&("UP".equals(ls)||"STARTING".equals(ls)));boolean autoEnabled=!rawActiveOrBusy()&&!layeredActiveOrBusy();autoButton.setEnabled(autoEnabled);smartButton.setEnabled(autoEnabled);customButton.setEnabled(autoEnabled);}
    private void setWgBusy(boolean b,String t){wgBusy=b;nativeStatusView.setText("Native Android VPN\n"+t);if(!b)refreshNativeState();}private void setAwgBusy(boolean b,String t){awgBusy=b;nativeStatusView.setText("Native Android VPN\n"+t);if(!b)refreshNativeState();}

    private boolean bundleReady(){if(getFileStreamPath(BUNDLE_FILE).isFile())return true;toast("Import/link a Router VPN node first");return false;}private JSONObject readBundle()throws Exception{try(FileInputStream in=openFileInput(BUNDLE_FILE)){return new JSONObject(new String(readLimited(in,32*1024*1024),StandardCharsets.UTF_8));}}
    private void openBundlePicker(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,IMPORT_BUNDLE);}
    @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==PREPARE_NATIVE_WG){if(result==RESULT_OK)connectNativeWireGuard();else statusView.setText("VPN permission denied; WireGuard stayed disconnected.");return;}if(code==PREPARE_NATIVE_AWG){if(result==RESULT_OK)connectNativeAmneziaWG();else statusView.setText("VPN permission denied; AmneziaWG stayed disconnected.");return;}if(code==PREPARE_LAYERED){if(result==RESULT_OK)startPendingLayered();else{pendingLayeredMode=null;statusView.setText("VPN permission denied; no layered session was created.");refreshNativeState();}return;}if(code==PREPARE_AUTO){if(result==RESULT_OK)startPendingAutomation();else{pendingCustomLayers=null;pendingSmart=false;statusView.setText("VPN permission denied; automatic mode selection did not start.");refreshNativeState();}return;}if(code!=IMPORT_BUNDLE||result!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IllegalStateException("Unable to open selected file");byte[]bytes=readLimited(in,32*1024*1024);JSONObject b=new JSONObject(new String(bytes,StandardCharsets.UTF_8));validateBundle(b);try(FileOutputStream out=openFileOutput(BUNDLE_FILE,MODE_PRIVATE)){out.write(bytes);}renderBundle(b);toast("Router node imported");if(!prefs().getBoolean(ONBOARDING_DONE,false))showOnboarding(false);}catch(Exception e){statusView.setText("Import failed: "+e.getMessage());}}
    private void loadSavedBundle(){try{JSONObject b=readBundle();validateBundle(b);renderBundle(b);}catch(Exception ignored){statusView.setText("No private Router VPN node linked yet.");}}private void validateBundle(JSONObject b){if(!b.has("profiles")||!b.has("modes")||!b.has("routerProfiles"))throw new IllegalArgumentException("This is not a complete Router VPN node bundle");if(!hasRawWireGuard(b)&&!hasRawAmneziaWG(b)&&b.optJSONObject("profiles")==null)throw new IllegalArgumentException("Router VPN node bundle has no usable profiles");}
    private void renderBundle(JSONObject b){String e=b.optString("endpoint","").trim(),h=b.optString("socks5Host","10.77.0.1").trim();int p=b.optInt("socks5Port",1080);socksAddress=h+":"+p;endpointView.setText("Endpoint\n"+(e.isEmpty()?"Choose/configure in client":e));socksView.setText("SOCKS5\n"+socksAddress+"\nAuthentication: none (tunnel/LAN only)");JSONArray modes=b.optJSONArray("modes");StringBuilder names=new StringBuilder();if(modes!=null)for(int i=0;i<modes.length();i++){JSONObject m=modes.optJSONObject(i);if(m==null)continue;if(names.length()>0)names.append('\n');names.append(m.optString("name",m.optString("id","unknown")));}modesView.setText("Modes in bundle\n"+(names.length()==0?"None":names));int direct=0;try{direct=singBox.listDirectLibboxModes(getFileStreamPath(BUNDLE_FILE)).size();}catch(Exception ignored){}statusView.setText("Private node stored app-private. Native raw WG/AWG plus "+direct+" direct libbox mode(s) are available; AUTO/SMART/CUSTOM prove the selected node before accepting a mode.");refreshNativeState();}
    private void copySocks(){if(socksAddress.isEmpty()){toast("Import the router bundle first");return;}ClipboardManager c=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Router VPN SOCKS5",socksAddress));toast("Copied "+socksAddress);}private void toast(String m){Toast.makeText(this,m,Toast.LENGTH_LONG).show();}
    private static byte[] readLimited(InputStream in,int max)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]b=new byte[8192];int total=0,n;while((n=in.read(b))!=-1){total+=n;if(total>max)throw new IllegalArgumentException("Bundle is larger than 32 MB");out.write(b,0,n);}return out.toByteArray();}
    private TextView text(String v,int sp,boolean bold){TextView x=new TextView(this);x.setText(v);x.setTextSize(sp);if(bold)x.setTypeface(x.getTypeface(),android.graphics.Typeface.BOLD);return x;}private TextView section(String h,String v){TextView x=text(h+"\n"+v,16,false);x.setPadding(dp(14),dp(14),dp(14),dp(14));x.setBackgroundColor(0xffeeeeee);return x;}private Button button(String l){Button b=new Button(this);b.setText(l);b.setAllCaps(false);b.setGravity(Gravity.CENTER);return b;}private LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(l,t,r,b);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
