package com.eabusham.routervpn;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.VpnService;
import android.os.Bundle;
import android.provider.Settings;
import android.text.InputType;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Unified native daily-use Android shell. */
public final class ProductActivity extends Activity {
    private static final String PREFS="router-vpn-unified";
    private static final String MODE_KEY="mode",CUSTOM_KEY="custom_presets",SELECTED_KIND="selected_kind",SELECTED_ID="selected_id";
    private static final String MULTI_ON="multihop_on",MULTI_ENTRY="multihop_entry",MULTI_EXIT="multihop_exit",MULTI_MODE="multihop_exit_mode";
    private static final int PREPARE_VIA_ENTRY_RTT=7606;
    private static final String STATE_PROBE_ENTRY="routervpn.via_entry_probe.entry",STATE_PROBE_CANDIDATES="routervpn.via_entry_probe.candidates";

    private AndroidNodeStore nodeStore; private AndroidStandardExitStore exitStore; private AndroidUnifiedNodeCatalog catalog; private AndroidUnifiedConnectionController connection; private AndroidTelemetry telemetry; private AndroidForwardingMaster forwardingMaster; private AndroidViaEntryLatencyProbe viaEntryProbe;
    private RouterVpnNodeMapView mapView; private LinearLayout sheet;
    private TextView nodeButton,statusView,modeHint,dnsHint,multihopHint,liveLatency,autoRequirementsHint;
    private Button connectButton,fastestButton,performanceButton,forwardButton;
    private CheckBox killSwitch,multihopToggle; private Spinner modeSpinner,dnsSpinner; private List<ModeChoice> modeChoices=new ArrayList<>();
    private float sheetTouchY; private boolean sheetExpanded,telemetryBusy,forwardingBusy; private long lastTelemetryAt; private double currentPathMs; private Boolean forwardingEnabled;
    private String pendingProbeEntryId=""; private ArrayList<String> pendingProbeCandidateIds=new ArrayList<>();

    private static final class ModeChoice { final String id,title; final List<String> layers; ModeChoice(String id,String title){this(id,title,Collections.emptyList());} ModeChoice(String id,String title,List<String>layers){this.id=id;this.title=title;this.layers=layers==null?Collections.emptyList():layers;} @Override public String toString(){return title;} }
    private static final class CustomPreset { String name; List<String> layers; CustomPreset(String name,List<String>layers){this.name=name;this.layers=layers;} }

    @Override protected void onCreate(Bundle state){super.onCreate(state);nodeStore=new AndroidNodeStore(this);exitStore=new AndroidStandardExitStore(this);catalog=new AndroidUnifiedNodeCatalog(nodeStore,exitStore);connection=new AndroidUnifiedConnectionController(this,nodeStore);telemetry=new AndroidTelemetry(this,nodeStore);forwardingMaster=new AndroidForwardingMaster(this,nodeStore);viaEntryProbe=new AndroidViaEntryLatencyProbe(this,AndroidRuntimeRegistry.get(this),telemetry);if(state!=null){pendingProbeEntryId=state.getString(STATE_PROBE_ENTRY,"");ArrayList<String> ids=state.getStringArrayList(STATE_PROBE_CANDIDATES);if(ids!=null)pendingProbeCandidateIds=ids;}setContentView(buildUi());refreshAll();if(state!=null)connection.restorePending(state,callback());AndroidProductOnboarding.showIfNeeded(this);}
    @Override protected void onResume(){super.onResume();refreshAll();if(viaEntryProbe!=null&&viaEntryProbe.isBusy()&&!pendingProbeEntryId.isEmpty())statusView.setText("Measuring live via-entry multihop candidate RTT…");}
    @Override protected void onSaveInstanceState(Bundle out){if(connection!=null)connection.savePending(out);if(!pendingProbeEntryId.isEmpty())out.putString(STATE_PROBE_ENTRY,pendingProbeEntryId);if(!pendingProbeCandidateIds.isEmpty())out.putStringArrayList(STATE_PROBE_CANDIDATES,new ArrayList<>(pendingProbeCandidateIds));super.onSaveInstanceState(out);}
    @Override protected void onDestroy(){if(connection!=null)connection.close();super.onDestroy();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){if(requestCode==PREPARE_VIA_ENTRY_RTT){if(resultCode==RESULT_OK)runPendingViaEntryProbe();else{AndroidNodeStore.Node entry=quietNode(pendingProbeEntryId);List<AndroidNodeStore.Node> exits=quietNodes(pendingProbeCandidateIds);clearPendingProbe();showViaEntryExitPicker(entry,exits,null,new IllegalStateException("Android VPN permission was not granted; via-entry RTT is unavailable."));}return;}if(connection!=null&&connection.onActivityResult(requestCode,resultCode)){refreshConnectionLater();return;}super.onActivityResult(requestCode,resultCode,data);}

    private View buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(10),dp(10),dp(8));root.setBackgroundColor(Color.rgb(8,16,30));
        nodeButton=text("Add / select node",14,true);nodeButton.setTextColor(Color.WHITE);nodeButton.setPadding(dp(12),dp(9),dp(12),dp(9));nodeButton.setBackground(round(Color.rgb(24,38,62),16));nodeButton.setOnClickListener(v->showNodes());root.addView(nodeButton,margins(0,0,0,dp(8)));
        mapView=new RouterVpnNodeMapView(this);mapView.setOnMarkerClickListener(marker->{String raw=marker.id==null?"":marker.id;int cut=raw.indexOf(':');if(cut<=0)return;selectCatalog(raw.substring(0,cut),raw.substring(cut+1));});LinearLayout.LayoutParams mapParams=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,0.56f);root.addView(mapView,mapParams);

        sheet=new LinearLayout(this);sheet.setOrientation(LinearLayout.VERTICAL);sheet.setPadding(dp(14),dp(5),dp(14),dp(12));sheet.setBackground(round(Color.rgb(17,27,45),24));sheet.setOnTouchListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_DOWN){sheetTouchY=event.getY();return false;}if(event.getAction()==MotionEvent.ACTION_UP){float delta=event.getY()-sheetTouchY;if(Math.abs(delta)>dp(40)){sheetExpanded=delta<0;applySheetWeight();}return false;}return false;});LinearLayout.LayoutParams sheetParams=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,0.44f);sheetParams.setMargins(0,dp(8),0,0);root.addView(sheet,sheetParams);
        TextView handle=text("━━━━━━━━",16,true);handle.setTextColor(Color.rgb(112,126,148));handle.setGravity(Gravity.CENTER);sheet.addView(handle);
        LinearLayout statusRow=row();statusView=text("Disconnected",13,false);statusView.setTextColor(Color.rgb(173,190,214));statusView.setTextIsSelectable(true);statusView.setOnClickListener(v->showConnectionDetails());statusRow.addView(statusView,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));Button connectionDetails=smallButton("Details / proof");connectionDetails.setOnClickListener(v->showConnectionDetails());statusRow.addView(connectionDetails);sheet.addView(statusRow,margins(0,0,0,dp(7)));

        LinearLayout connectRow=row();fastestButton=smallButton("⚡ Fastest ▾");fastestButton.setContentDescription("Select the fastest measured Router VPN node or choose a specific node. Use Connect separately.");fastestButton.setOnClickListener(v->showFastConnectMenu());connectRow.addView(fastestButton);connectButton=primaryButton("Connect");connectButton.setOnClickListener(v->connectOrDisconnect());connectRow.addView(connectButton,new LinearLayout.LayoutParams(0,dp(50),1f));liveLatency=text("-- ms",11,true);liveLatency.setTextColor(Color.rgb(173,190,214));liveLatency.setGravity(Gravity.CENTER);liveLatency.setPadding(dp(6),0,dp(6),0);connectRow.addView(liveLatency);killSwitch=new CheckBox(this);killSwitch.setText("Kill");killSwitch.setContentDescription("Kill switch");killSwitch.setTextColor(Color.WHITE);killSwitch.setButtonTintList(ColorStateList.valueOf(Color.rgb(123,104,255)));killSwitch.setOnCheckedChangeListener((b,on)->{if(!b.isPressed())return;setQuickKillSwitch(on);});connectRow.addView(killSwitch);forwardButton=smallButton("Forward");forwardButton.setContentDescription("Server port-forwarding master");forwardButton.setOnClickListener(v->showForwarding());connectRow.addView(forwardButton);sheet.addView(connectRow);

        LinearLayout multiRow=row();multihopToggle=new CheckBox(this);multihopToggle.setText("Multihop");multihopToggle.setTextColor(Color.WHITE);multihopToggle.setButtonTintList(ColorStateList.valueOf(Color.rgb(55,145,255)));multihopToggle.setOnCheckedChangeListener((b,on)->{if(!b.isPressed())return;if(mutationBusy()){toast("Finish/disconnect the current VPN operation before changing multihop configuration.");refreshMultihopSummary();return;}prefs().edit().putBoolean(MULTI_ON,on).apply();refreshMap();refreshMultihopSummary();refreshTelemetry(true);});multiRow.addView(multihopToggle);multihopHint=text("Off",11,false);multihopHint.setTextColor(Color.rgb(173,190,214));multiRow.addView(multihopHint,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));Button hops=smallButton("Edit hops");hops.setOnClickListener(v->configureMultihop());multiRow.addView(hops);sheet.addView(multiRow,margins(0,dp(8),0,0));

        LinearLayout settingsRow=controlRow("Settings");Button settings=smallButton("Open settings");settings.setOnClickListener(v->showSettings());settingsRow.addView(settings);Button connectionProfiles=smallButton("Connections");connectionProfiles.setContentDescription("Add, load, update or delete a whole non-secret connection profile");connectionProfiles.setOnClickListener(v->showConnectionProfiles());settingsRow.addView(connectionProfiles);performanceButton=smallButton("Performance");performanceButton.setOnClickListener(v->showPerformance());settingsRow.addView(performanceButton);Button mtu=smallButton("MTU");mtu.setOnClickListener(v->showMtuHelp());settingsRow.addView(mtu);sheet.addView(settingsRow,margins(0,dp(7),0,0));autoRequirementsHint=text("AUTO requirements: Off",11,false);autoRequirementsHint.setTextColor(Color.rgb(145,160,184));autoRequirementsHint.setPadding(dp(72),0,0,0);sheet.addView(autoRequirementsHint);
        LinearLayout modeRow=controlRow("Mode");modeSpinner=new Spinner(this);modeSpinner.setPopupBackgroundDrawable(round(Color.rgb(29,43,68),12));modeRow.addView(modeSpinner,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));Button modeDetails=smallButton("Presets");modeDetails.setOnClickListener(v->AndroidProductParity.showModes(this,nodeStore));modeRow.addView(modeDetails);sheet.addView(modeRow,margins(0,dp(7),0,0));modeHint=text("SMART AUTO is the default.",11,false);modeHint.setTextColor(Color.rgb(145,160,184));sheet.addView(modeHint);
        LinearLayout dnsRow=controlRow("DNS");dnsSpinner=new Spinner(this);String[]dns={"Home AdGuard","Fastest measured","Custom","DoT","DoH","DoH3","Rescue"};dnsSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,dns));dnsRow.addView(dnsSpinner,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));Button dnsDetails=smallButton("Details");dnsDetails.setOnClickListener(v->AndroidProductParity.showDNS(this,nodeStore));dnsRow.addView(dnsDetails);sheet.addView(dnsRow,margins(0,dp(7),0,0));dnsHint=text("DNS changes the next tunnel resolver path; Connected still requires runtime DNS/path proof.",11,false);dnsHint.setTextColor(Color.rgb(145,160,184));sheet.addView(dnsHint);dnsSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean ready;public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){if(!ready){ready=true;return;}if(mutationBusy()){toast("Disconnect/finish the current VPN operation before changing DNS.");refreshDnsSelection();return;}if(pos==0)setQuickDns("home");else if(pos==1)setQuickDns("fastest");else if(pos==6)setQuickDns("rescue");else AndroidProductParity.showDNS(ProductActivity.this,nodeStore);}});
        LinearLayout footer=row();Button nodes=smallButton("Nodes");nodes.setContentDescription("Add / manage nodes");nodes.setOnClickListener(v->showNodes());footer.addView(nodes);Button profiles=smallButton("Router nodes");profiles.setContentDescription("Manage linked Router VPN node records");profiles.setOnClickListener(v->showProfileManager());footer.addView(profiles);Button pair=smallButton("Add Router");pair.setOnClickListener(v->showPairDialog());footer.addView(pair);Button custom=smallButton("Add custom");custom.setOnClickListener(v->openStandardExits());footer.addView(custom);Button help=smallButton("Help");help.setOnClickListener(v->showHelp());footer.addView(help);sheet.addView(footer,margins(0,dp(8),0,0));return root;
    }

    private void applySheetWeight(){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)sheet.getLayoutParams();p.weight=sheetExpanded?0.70f:0.44f;sheet.setLayoutParams(p);LinearLayout.LayoutParams m=(LinearLayout.LayoutParams)mapView.getLayoutParams();m.weight=sheetExpanded?0.30f:0.56f;mapView.setLayoutParams(m);}
    private void refreshAll(){refreshNodes();refreshModeChoices();refreshConnectionState();refreshSettingsState();refreshDnsSelection();refreshMultihopSummary();refreshTelemetry(false);refreshForwardingState();}
    private boolean mutationBusy(){return AndroidVpnMutationGuard.isBusy(this)||(viaEntryProbe!=null&&viaEntryProbe.isBusy());}
    private void refreshConnectionLater(){mapView.postDelayed(this::refreshAll,350);mapView.postDelayed(this::refreshAll,1300);mapView.postDelayed(this::refreshAll,3000);}

    private void connectOrDisconnect(){if(viaEntryProbe.isBusy()){toast("Via-entry candidate RTT is still being measured; the temporary entry will disconnect automatically first.");return;}if(connection.isActiveOrTransitioning()){statusView.setText("Disconnecting…");connectButton.setText("Disconnecting…");connection.disconnect(callback());return;}AndroidUnifiedNodeCatalog.Item selected=selectedCatalogItem();if(selected==null){showNodes();return;}if(!selected.isRouterVpn()){Intent intent=new Intent(this,StandardExitActivity.class);intent.putExtra(StandardExitActivity.EXTRA_EXIT_ID,selected.id);startActivity(intent);return;}if(multihopToggle.isChecked()){try{AndroidNodeStore.Node entry=nodeById(prefs().getString(MULTI_ENTRY,"")),exit=nodeById(prefs().getString(MULTI_EXIT,""));String exitMode=prefs().getString(MULTI_MODE,"");if(entry==null||exit==null||exitMode.isEmpty()){configureMultihop();return;}statusView.setText("Preparing multihop…");connection.connectMultihop(entry,exit,exitMode,callback());}catch(Exception error){toast(safe(error));}return;}ModeChoice choice=currentMode();if(choice==null){refreshModeChoices();choice=currentMode();if(choice==null)return;}statusView.setText("Preparing "+choice.title+"…");connection.connect(choice.id,choice.layers,callback());}
    private AndroidUnifiedConnectionController.Callback callback(){return new AndroidUnifiedConnectionController.Callback(){public void progress(String message){runOnUiThread(()->{if(isFinishing()||isDestroyed())return;statusView.setText(message);connectButton.setText("Disconnect");});}public void finished(boolean ok,String message){runOnUiThread(()->{if(isFinishing()||isDestroyed())return;statusView.setText(message);if(!ok)toast(message);refreshAll();refreshConnectionLater();});}};}
    private void refreshConnectionState(){boolean active=connection!=null&&connection.isActiveOrTransitioning(),busy=mutationBusy();connectButton.setText(active?"Disconnect":"Connect");nodeButton.setEnabled(!busy);fastestButton.setEnabled(!busy);killSwitch.setEnabled(!busy);multihopToggle.setEnabled(!busy);modeSpinner.setEnabled(!busy);dnsSpinner.setEnabled(!busy);if(!viaEntryProbe.isBusy())statusView.setText(AndroidHomeSummary.format(this,nodeStore));if(!connection.isConnected()){currentPathMs=0;liveLatency.setText("-- ms");}}

    private void showConnectionDetails(){String truth=AndroidHomeSummary.format(this,nodeStore);new AlertDialog.Builder(this).setTitle("Connection details & proof").setMessage(truth+"\n\nConnected is not treated as a proved public exit until the current app-owned VPN network, frozen session node/path and current-session exit proof all agree.").setPositiveButton("Prove actual exit",(d,w)->{statusView.setText("Proving actual public VPN exit for this session…");AndroidHomeSummary.proveActualExit(this,nodeStore,(message,error)->runOnUiThread(()->{statusView.setText(message);if(error!=null)toast(message);refreshAll();}));}).setNeutralButton("Emergency disconnect",(d,w)->{statusView.setText("Emergency disconnect requested…");AndroidHomeSummary.emergencyDisconnect(this,(message,error)->runOnUiThread(()->{statusView.setText(message);if(error!=null)toast(message);refreshAll();refreshConnectionLater();}));}).setNegativeButton("Close",null).show();}

    private void showFastConnectMenu(){if(mutationBusy()){toast("Disconnect/finish the current VPN operation before changing the selected fastest node.");return;}fastestButton.setEnabled(false);fastestButton.setText("Testing…");telemetry.measureAll(3,(values,error)->runOnUiThread(()->{fastestButton.setEnabled(true);refreshNodes();if(error!=null){toast("Fastest-node test failed: "+safe(error));return;}if(values==null||values.isEmpty()){toast("No measurable Router VPN nodes are available.");return;}String[]labels=new String[values.size()+1];labels[0]="⚡ Fastest — "+values.get(0).name+" • "+values.get(0).shortLabel();for(int i=0;i<values.size();i++)labels[i+1]=values.get(i).name+" • "+values.get(i).shortLabel();new AlertDialog.Builder(this).setTitle("Select node").setMessage("Live TCP RTT is lightweight. Selecting a target does not connect; use the separate Connect button when ready. The 50-sample Performance test remains the durable benchmark.").setItems(labels,(d,w)->{if(mutationBusy()){toast("VPN state changed while Fastest was measuring; disconnect/finish before selecting another node.");return;}AndroidTelemetry.Result pick=values.get(w==0?0:w-1);try{nodeStore.select(pick.id);prefs().edit().putString(SELECTED_KIND,"router-vpn").putString(SELECTED_ID,pick.id).apply();refreshAll();toast("Selected "+pick.name+". Press Connect when ready.");}catch(Exception e){toast(safe(e));}}).setNegativeButton("Cancel",null).show();}));}

    private void refreshTelemetry(boolean force){long now=System.currentTimeMillis();if(telemetryBusy||viaEntryProbe.isBusy()||(!force&&now-lastTelemetryAt<1800))return;lastTelemetryAt=now;AndroidHomeStateStore.Snapshot home=AndroidHomeStateStore.snapshot(this);boolean connected=connection!=null&&connection.isConnected()&&!"external".equals(home.logicalMode);if(connected){telemetryBusy=true;telemetry.currentPath(2,(path,error)->runOnUiThread(()->{telemetryBusy=false;if(error==null&&path!=null){currentPathMs=path.medianMs;liveLatency.setText(String.format(Locale.US,"%.1f ms",path.medianMs));}else{currentPathMs=0;liveLatency.setText("-- ms");}refreshMultihopSummary();}));}else{currentPathMs=0;liveLatency.setText("-- ms");}refreshMultihopTelemetry();}
    private void refreshMultihopTelemetry(){String entryId,exitId;if(connection.isMultihopConnected()){entryId=connection.activeMultihopEntryId();exitId=connection.activeMultihopExitId();}else{if(!prefs().getBoolean(MULTI_ON,false))return;entryId=prefs().getString(MULTI_ENTRY,"");exitId=prefs().getString(MULTI_EXIT,"");}try{AndroidNodeStore.Node entry=nodeById(entryId),exit=nodeById(exitId);if(entry==null||exit==null)return;if(telemetry.cachedMedian(entry.id)<=0)telemetry.measureNode(entry,2,(r,e)->runOnUiThread(()->{refreshMap();refreshMultihopSummary();}));if(telemetry.cachedMedian(exit.id)<=0)telemetry.measureNode(exit,2,(r,e)->runOnUiThread(()->{refreshMap();refreshMultihopSummary();}));}catch(Exception ignored){}}

    private void showPerformance(){String[]actions={"Live current tunnel RTT","50-sample selected node","Benchmark all Router nodes","Real current VPN path speed","Routed multihop speeds","Path throughput / Auto MTU status"};new AlertDialog.Builder(this).setTitle("Performance").setMessage("RTT and Mbps are separate real measurements. Real path speed transfers 8 MiB down and 8 MiB up against the authenticated private router-agent through Android's active VPN route. Routed multihop speed independently contacts each actual live hop through the current routing graph; unreachable hops remain unavailable rather than being derived from RTT arithmetic.").setItems(actions,(d,w)->{if(w==0){if(!connection.isConnected()){toast("Connect first for current tunnel RTT.");return;}telemetry.currentPath(5,(r,e)->runOnUiThread(()->dialog("Live tunnel RTT",e==null&&r!=null?String.format(Locale.US,"Median %.1f ms • %d ok / %d failed\n%s",r.medianMs,r.samples,r.failed,r.proof):safe(e))));}else if(w==1){try{AndroidNodeStore.Node n=nodeById(nodeStore.activeId());if(n==null)throw new IllegalStateException("Select a Router VPN node first.");toast("Running 50 samples…");telemetry.measureNode(n,50,(r,e)->runOnUiThread(()->{if(e!=null)toast(safe(e));else{dialog("50-sample node benchmark",r.detail());refreshMap();}}));}catch(Exception e){toast(safe(e));}}else if(w==2){toast("Benchmarking linked Router nodes…");telemetry.measureAll(5,(values,e)->runOnUiThread(()->{if(e!=null){toast(safe(e));return;}StringBuilder out=new StringBuilder();for(AndroidTelemetry.Result r:values)out.append(r.detail()).append('\n');dialog("Node benchmark",out.toString());refreshMap();}));}else if(w==3){if(!connection.isConnected()){toast("Connect Router VPN before testing current path speed.");return;}toast("Testing 8 MiB down + 8 MiB up through the active VPN path…");telemetry.speedTest(8<<20,(r,e)->runOnUiThread(()->{if(e!=null)dialog("Real VPN path speed",safe(e));else dialog("Real VPN path speed",r.detail()+"\n\nProof: authenticated bounded private router-agent transfer through the frozen current Android VPN session path.");}));}else if(w==4){runRoutedHopSpeeds();}else{JSONObject p=activeRouterProfile();if(p==null){toast("Select a Router VPN node first.");return;}double mbps=p.optDouble("effective_mtu_mbps",0),rtt=p.optDouble("effective_mtu_median_rtt_ms",0);int mtu=p.optInt("effective_mtu",0);String value=mbps>0?String.format(Locale.US,"Last MTU-path optimizer result: %.1f Mbps • MTU %d • RTT %.1f ms\n\nThis is separate from the real 8 MiB down/up path speed test.",mbps,mtu,rtt):"No proven Auto-MTU optimizer result is stored for this path yet. Open Settings / MTU to configure Auto or Fixed MTU. Real path Mbps is a separate Performance action.";dialog("Path throughput / Auto MTU",value);}}).setNegativeButton("Close",null).show();}

    private void runRoutedHopSpeeds(){
        if(!connection.isMultihopConnected()){toast("Connect the actual Android multihop graph before testing routed hop speeds.");return;}
        try{
            AndroidNodeStore.Node entry=nodeById(connection.activeMultihopEntryId()),exit=nodeById(connection.activeMultihopExitId());
            if(entry==null||exit==null||entry.id.equals(exit.id))throw new IllegalStateException("Active multihop graph identity is unavailable.");
            toast("Testing routed entry and exit hop speeds…");
            telemetry.speedTest(entry,8<<20,(entryResult,entryError)->telemetry.speedTest(exit,8<<20,(exitResult,exitError)->runOnUiThread(()->{
                String entryText=entryError==null&&entryResult!=null?entryResult.detail():"Unavailable: "+safe(entryError);
                String exitText=exitError==null&&exitResult!=null?exitResult.detail():"Unavailable: "+safe(exitError);
                dialog("Routed multihop speeds","ENTRY • "+entry.name+"\n"+entryText+"\n\nEXIT • "+exit.name+"\n"+exitText+"\n\nProof: each row independently contacts that exact runtime hop's authenticated private router-agent through the live Android VPN routing graph. These values are not inferred segment bandwidth.");
            })));
        }catch(Exception error){toast(safe(error));}
    }

    private void refreshModeChoices(){String wanted=prefs().getString(MODE_KEY,"smart-auto");List<ModeChoice> values=new ArrayList<>();values.add(new ModeChoice("smart-auto","SMART AUTO — recommended"));values.add(new ModeChoice("auto","AUTO — first proven path"));try{JSONObject root=activeBundle();JSONArray logical=root.optJSONArray("logicalModes");if(logical!=null)for(int i=0;i<logical.length();i++){JSONObject m=logical.optJSONObject(i);if(m==null)continue;String id=m.optString("id","");if(id.isEmpty())continue;values.add(new ModeChoice(id,m.optString("name",id)));}}catch(Exception ignored){}for(CustomPreset p:loadCustomPresets())values.add(new ModeChoice("custom:"+p.name,"CUSTOM • "+p.name,p.layers));values.add(new ModeChoice("custom:new","New CUSTOM preset…"));modeChoices=values;ArrayAdapter<ModeChoice> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values);modeSpinner.setAdapter(adapter);int index=0;for(int i=0;i<values.size();i++)if(values.get(i).id.equals(wanted)){index=i;break;}modeSpinner.setSelection(index,false);modeSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean ready;public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){if(!ready){ready=true;return;}if(pos<0||pos>=modeChoices.size())return;if(mutationBusy()){toast("Disconnect/finish the current VPN operation before changing the next connection mode or CUSTOM preset.");refreshModeChoices();return;}ModeChoice selected=modeChoices.get(pos);if("custom:new".equals(selected.id)){showCustomBuilder(null);return;}prefs().edit().putString(MODE_KEY,selected.id).apply();modeHint.setText(selected.id.startsWith("custom:")?"Saved visual CUSTOM preset • exact required layers":"Unavailable presets remain visible; the engine fails closed with the exact readiness/proof reason.");}});}
    private ModeChoice currentMode(){if(modeSpinner==null||modeChoices.isEmpty())return null;int i=modeSpinner.getSelectedItemPosition();return i>=0&&i<modeChoices.size()?modeChoices.get(i):modeChoices.get(0);}
    private void showCustomBuilder(CustomPreset editing){if(mutationBusy()){toast("Disconnect/finish the current VPN operation before creating, editing or deleting CUSTOM presets.");return;}try{List<String> layers=allCatalogLayers();if(layers.isEmpty()){toast("No mode layers are available in the selected Router VPN bundle.");return;}LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(8),dp(18),0);EditText name=new EditText(this);name.setHint("Preset name");if(editing!=null)name.setText(editing.name);body.addView(name);body.addView(text("Select exact required layers. Router VPN tries only native Android stacks containing every selected layer and fails closed if no compatible path passes proof.",12,false));boolean[] checked=new boolean[layers.size()];Set<String> old=editing==null?Collections.emptySet():new LinkedHashSet<>(editing.layers);for(int i=0;i<layers.size();i++)checked[i]=old.contains(layers.get(i));AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(editing==null?"New CUSTOM preset":"Edit CUSTOM • "+editing.name).setView(body).setMultiChoiceItems(layers.toArray(new CharSequence[0]),checked,(d,w,on)->checked[w]=on).setPositiveButton("Save",null).setNeutralButton(editing==null?"Cancel":"Delete",null).setNegativeButton("Cancel",null);AlertDialog dialog=b.create();dialog.setOnShowListener(x->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(mutationBusy()){toast("VPN state changed; disconnect/finish before saving CUSTOM presets.");return;}String n=name.getText().toString().trim();List<String> selected=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])selected.add(layers.get(i));if(n.isEmpty()||n.length()>64){toast("Preset name must be 1–64 characters.");return;}if(selected.isEmpty()){toast("CUSTOM requires at least one layer.");return;}saveCustomPreset(new CustomPreset(n,selected),editing==null?null:editing.name);prefs().edit().putString(MODE_KEY,"custom:"+n).apply();dialog.dismiss();refreshModeChoices();});if(editing!=null)dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{if(mutationBusy()){toast("VPN state changed; disconnect/finish before deleting CUSTOM presets.");return;}deleteCustomPreset(editing.name);prefs().edit().putString(MODE_KEY,"smart-auto").apply();dialog.dismiss();refreshModeChoices();});});dialog.show();}catch(Exception error){toast("CUSTOM builder unavailable: "+safe(error));}}

    private void refreshNodes(){if(catalog==null||mapView==null)return;try{List<AndroidUnifiedNodeCatalog.Item>items=catalog.list(AndroidUnifiedNodeCatalog.SORT_CURRENT);String selectedKind=prefs().getString(SELECTED_KIND,"router-vpn"),selectedId=prefs().getString(SELECTED_ID,nodeStore.activeId());if(selectedId.isEmpty()&&!items.isEmpty()&&!mutationBusy()){AndroidUnifiedNodeCatalog.Item first=items.get(0);selectedKind=first.kind;selectedId=first.id;if(first.isRouterVpn())nodeStore.select(first.id);prefs().edit().putString(SELECTED_KIND,selectedKind).putString(SELECTED_ID,selectedId).apply();}List<RouterVpnNodeMapView.Marker>markers=new ArrayList<>();String entry,exit;boolean multi;if(connection.isMultihopConnected()){entry=connection.activeMultihopEntryId();exit=connection.activeMultihopExitId();multi=true;}else{entry=prefs().getString(MULTI_ENTRY,"");exit=prefs().getString(MULTI_EXIT,"");multi=prefs().getBoolean(MULTI_ON,false);}AndroidUnifiedNodeCatalog.Item chosen=null;for(AndroidUnifiedNodeCatalog.Item item:items){if(item.kind.equals(selectedKind)&&item.id.equals(selectedId))chosen=item;if(!item.hasCoordinates())continue;String role;if(multi&&item.isRouterVpn()&&item.id.equals(entry))role=RouterVpnNodeMapView.ROLE_ENTRY;else if(multi&&item.isRouterVpn()&&item.id.equals(exit))role=RouterVpnNodeMapView.ROLE_EXIT;else if(item.id.equals(selectedId)&&item.kind.equals(selectedKind))role=RouterVpnNodeMapView.ROLE_SELECTED;else if(!item.isRouterVpn())role=RouterVpnNodeMapView.ROLE_EXTERNAL;else role=RouterVpnNodeMapView.ROLE_NORMAL;double ms=telemetry==null?0:telemetry.cachedMedian(item.id);if(ms<=0&&item.hasMeasuredLatency())ms=item.latencyMedianMs;markers.add(new RouterVpnNodeMapView.Marker(item.kind+":"+item.id,item.name,item.latitude,item.longitude,role,ms));}mapView.setMarkers(markers);nodeButton.setText(chosen==null?"Add / select node":(chosen.isRouterVpn()?"Router • ":"Custom • ")+chosen.name+(telemetry!=null&&telemetry.cachedMedian(chosen.id)>0?String.format(Locale.US," • %.1f ms",telemetry.cachedMedian(chosen.id)):"")+"  ▾");if(fastestButton!=null)fastestButton.setText(chosen==null?"⚡ Fastest ▾":"⚡ "+chosen.name+" ▾");}catch(Exception error){nodeButton.setText("Node catalog unavailable");if(fastestButton!=null)fastestButton.setText("⚡ Fastest ▾");mapView.setMarkers(new ArrayList<>());}}
    private void refreshMap(){refreshNodes();}
    private AndroidUnifiedNodeCatalog.Item selectedCatalogItem(){try{String kind=prefs().getString(SELECTED_KIND,"router-vpn"),id=prefs().getString(SELECTED_ID,nodeStore.activeId());for(AndroidUnifiedNodeCatalog.Item item:catalog.list(AndroidUnifiedNodeCatalog.SORT_CURRENT))if(item.kind.equals(kind)&&item.id.equals(id))return item;}catch(Exception ignored){}return null;}
    private void selectCatalog(String kind,String id){try{for(AndroidUnifiedNodeCatalog.Item item:catalog.list(AndroidUnifiedNodeCatalog.SORT_CURRENT))if(item.kind.equals(kind)&&item.id.equals(id)){selectCatalog(item);return;}}catch(Exception error){toast(safe(error));}}
    private void selectCatalog(AndroidUnifiedNodeCatalog.Item item){if(mutationBusy()){toast("Disconnect/finish the current VPN operation before changing the selected node; live/probe identity is frozen.");return;}try{if(item.isRouterVpn())nodeStore.select(item.id);prefs().edit().putString(SELECTED_KIND,item.kind).putString(SELECTED_ID,item.id).apply();refreshAll();}catch(Exception error){toast(safe(error));}}
    private void showNodes(){try{List<AndroidUnifiedNodeCatalog.Item>items=catalog.list(AndroidUnifiedNodeCatalog.SORT_CURRENT);if(items.isEmpty()){new AlertDialog.Builder(this).setTitle("Nodes").setMessage("No nodes yet. Add a Router node by secure LAN pairing, or add a Custom / external exit.").setPositiveButton("Add Router node",(d,w)->showPairDialog()).setNeutralButton("Add custom",(d,w)->openStandardExits()).setNegativeButton("Close",null).show();return;}String[]labels=new String[items.size()];for(int i=0;i<items.size();i++){AndroidUnifiedNodeCatalog.Item item=items.get(i);double ms=telemetry.cachedMedian(item.id);labels[i]=(item.isRouterVpn()?"Router • ":"Custom • ")+item.name+(ms>0?String.format(Locale.US," • %.1f ms",ms):"")+(item.hasCoordinates()?"":" • list only");}new AlertDialog.Builder(this).setTitle("Choose node").setMessage(mutationBusy()?"The current live/probe identity is frozen. Disconnect/finish before selecting another node.":"One node is selected by default. Only real stored coordinates appear on the globe; no IP geolocation/fake pins.").setItems(labels,(d,w)->selectCatalog(items.get(w))).setPositiveButton("Add Router node",(d,w)->showPairDialog()).setNeutralButton("Add custom",(d,w)->openStandardExits()).setNegativeButton("Close",null).show();}catch(Exception error){toast(safe(error));}}

    private void showConnectionProfiles(){
        AndroidConnectionProfilesDialog.show(this,nodeStore,exitStore,this::refreshAll);
    }

    private void showProfileManager(){try{List<AndroidNodeStore.Node>nodes=nodeStore.list();if(nodes.isEmpty()){new AlertDialog.Builder(this).setTitle("Profiles").setMessage("No Router VPN profiles are stored. Pair/import one, or open Custom exits for standard external profiles.").setPositiveButton("Add Router",(d,w)->showPairDialog()).setNeutralButton("Custom exits",(d,w)->openStandardExits()).setNegativeButton("Close",null).show();return;}String[]labels=new String[nodes.size()];for(int i=0;i<nodes.size();i++)labels[i]=(nodes.get(i).id.equals(nodeStore.activeId())?"✓ ":"")+nodes.get(i).name+(telemetry.cachedMedian(nodes.get(i).id)>0?String.format(Locale.US," • %.1f ms",telemetry.cachedMedian(nodes.get(i).id)):"");new AlertDialog.Builder(this).setTitle("Router profiles").setMessage("Select, update/re-pair, benchmark or delete. Re-pairing the same stable node identity updates its stored profile rather than creating a duplicate. Live sessions freeze profile identity until disconnect.").setItems(labels,(d,w)->showProfileActions(nodes.get(w))).setPositiveButton("Add / update via pairing",(d,w)->showPairDialog()).setNeutralButton("Custom profiles",(d,w)->openStandardExits()).setNegativeButton("Close",null).show();}catch(Exception e){toast(safe(e));}}
    private void showProfileActions(AndroidNodeStore.Node node){String[]a={"Select","50-sample benchmark","Update / re-pair","Delete"};new AlertDialog.Builder(this).setTitle(node.name).setItems(a,(d,w)->{try{if(w==0){if(mutationBusy()){toast("Disconnect/finish before selecting another Router profile.");return;}nodeStore.select(node.id);prefs().edit().putString(SELECTED_KIND,"router-vpn").putString(SELECTED_ID,node.id).apply();refreshAll();}else if(w==1){toast("Running 50 samples…");telemetry.measureNode(node,50,(r,e)->runOnUiThread(()->{if(e!=null)toast(safe(e));else{dialog("Profile benchmark",r.detail());refreshAll();}}));}else if(w==2)showPairDialog();else new AlertDialog.Builder(this).setTitle("Delete "+node.name+"?").setMessage("Only this app-private Router VPN profile is removed.").setPositiveButton("Delete",(x,y)->{if(mutationBusy()){toast("Disconnect/finish before deleting a Router profile.");return;}try{nodeStore.remove(node.id);refreshAll();}catch(Exception e){toast(safe(e));}}).setNegativeButton("Cancel",null).show();}catch(Exception e){toast(safe(e));}}).setNegativeButton("Close",null).show();}

    private void configureMultihop(){if(mutationBusy()){toast("Disconnect/finish the current VPN operation before editing multihop hops.");return;}try{List<AndroidNodeStore.Node>nodes=nodeStore.list();if(nodes.size()<2){toast("Multihop needs at least two different Router VPN nodes.");return;}String[]labels=new String[nodes.size()];for(int i=0;i<nodes.size();i++)labels[i]=nodes.get(i).name+(telemetry.cachedMedian(nodes.get(i).id)>0?String.format(Locale.US," • direct %.1f ms",telemetry.cachedMedian(nodes.get(i).id)):"");new AlertDialog.Builder(this).setTitle("Multihop entry").setMessage("Choose hop 1. Router VPN will then briefly establish and prove this entry so candidate hop-2 RTTs are measured through it, not calculated from direct RTTs.").setItems(labels,(d,w)->prepareViaEntryExitMeasurement(nodes.get(w),nodes)).setNegativeButton("Cancel",null).show();}catch(Exception error){toast(safe(error));}}
    private void prepareViaEntryExitMeasurement(AndroidNodeStore.Node entry,List<AndroidNodeStore.Node>all){if(mutationBusy()){toast("VPN state changed; disconnect/finish before measuring multihop candidates.");return;}List<AndroidNodeStore.Node>exits=new ArrayList<>();for(AndroidNodeStore.Node n:all)if(!n.id.equals(entry.id))exits.add(n);if(exits.isEmpty()){toast("No different exit nodes are available.");return;}pendingProbeEntryId=entry.id;pendingProbeCandidateIds=new ArrayList<>();for(AndroidNodeStore.Node n:exits)pendingProbeCandidateIds.add(n.id);Intent permission=VpnService.prepare(this);if(permission!=null){statusView.setText("Waiting for Android VPN permission to measure "+entry.name+" → candidate RTT…");startActivityForResult(permission,PREPARE_VIA_ENTRY_RTT);}else runPendingViaEntryProbe();}
    private void runPendingViaEntryProbe(){if(mutationBusy()&&!viaEntryProbe.isBusy()){clearPendingProbe();toast("VPN state changed while permission was open; disconnect/finish before measuring multihop candidates.");refreshAll();return;}AndroidNodeStore.Node entry=quietNode(pendingProbeEntryId);List<AndroidNodeStore.Node> exits=quietNodes(pendingProbeCandidateIds);if(entry==null||exits.isEmpty()){clearPendingProbe();toast("Multihop candidate measurement state expired; choose the entry again.");return;}statusView.setText("Preparing real "+entry.name+" → candidate RTT measurement…");viaEntryProbe.measure(entry,exits,5,new AndroidViaEntryLatencyProbe.Callback(){public void progress(String message){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())statusView.setText(message);});}public void finished(AndroidNodeStore.Node measuredEntry,List<AndroidTelemetry.Result>values,Throwable error){runOnUiThread(()->{List<AndroidNodeStore.Node>currentExits=quietNodes(pendingProbeCandidateIds);clearPendingProbe();if(isFinishing()||isDestroyed())return;refreshAll();showViaEntryExitPicker(measuredEntry,currentExits,values,error);});}});}
    private void showViaEntryExitPicker(AndroidNodeStore.Node entry,List<AndroidNodeStore.Node>exits,List<AndroidTelemetry.Result>values,Throwable measurementError){if(entry==null||exits==null||exits.isEmpty()){toast("Multihop candidate exits are unavailable.");return;}Map<String,AndroidTelemetry.Result>byId=new HashMap<>();if(values!=null)for(AndroidTelemetry.Result r:values)byId.put(r.id,r);String[]labels=new String[exits.size()];for(int i=0;i<exits.size();i++){AndroidTelemetry.Result r=byId.get(exits.get(i).id);labels[i]=entry.name+" → "+exits.get(i).name+" • "+(r==null?"unavailable":String.format(Locale.US,"%.1f ms",r.medianMs));}String note=measurementError==null?"Each RTT was measured while a proven temporary WireGuard tunnel to the selected entry was actually routing the device. That temporary tunnel is already disconnected. Values are not saved as direct-node RTTs.":"Via-entry RTT could not be proven: "+safe(measurementError)+"\n\nCandidates remain selectable, but Router VPN shows ‘unavailable’ instead of substituting direct RTT arithmetic.";new AlertDialog.Builder(this).setTitle("Multihop hop 2 • live via "+entry.name).setMessage(note).setItems(labels,(d,w)->chooseMultihopMode(entry,exits.get(w))).setNegativeButton("Cancel",null).show();}
    private void clearPendingProbe(){pendingProbeEntryId="";pendingProbeCandidateIds.clear();}
    private AndroidNodeStore.Node quietNode(String id){try{return nodeById(id);}catch(Exception ignored){return null;}}
    private List<AndroidNodeStore.Node> quietNodes(List<String> ids){List<AndroidNodeStore.Node>out=new ArrayList<>();if(ids==null)return out;try{List<AndroidNodeStore.Node>all=nodeStore.list();for(String id:ids)for(AndroidNodeStore.Node node:all)if(node.id.equals(id)){out.add(node);break;}}catch(Exception ignored){}return out;}
    private void chooseMultihopMode(AndroidNodeStore.Node entry,AndroidNodeStore.Node exit){if(mutationBusy()){toast("VPN state changed; disconnect/finish before editing multihop.");return;}try{List<NativeSingBoxController.ModeInfo>modes=connection.supportedMultihopExitModes(exit);if(modes.isEmpty()){toast("That exit has no proven Android Shadowsocks/Hysteria2 multihop transport.");return;}String[]labels=new String[modes.size()];for(int i=0;i<modes.size();i++)labels[i]=modes.get(i).name+" ["+modes.get(i).id+"]";new AlertDialog.Builder(this).setTitle("Exit transport").setItems(labels,(d,w)->{if(mutationBusy()){toast("VPN state changed; disconnect/finish before saving multihop.");return;}prefs().edit().putBoolean(MULTI_ON,true).putString(MULTI_ENTRY,entry.id).putString(MULTI_EXIT,exit.id).putString(MULTI_MODE,modes.get(w).id).apply();multihopToggle.setChecked(true);telemetry.measureNode(entry,3,(a,b)->runOnUiThread(this::refreshAll));telemetry.measureNode(exit,3,(a,b)->runOnUiThread(this::refreshAll));refreshAll();}).setNegativeButton("Cancel",null).show();}catch(Exception error){toast(safe(error));}}
    private void refreshMultihopSummary(){boolean live=connection.isMultihopConnected();boolean on=live||prefs().getBoolean(MULTI_ON,false);multihopToggle.setChecked(on);if(!on){multihopHint.setText("Off");return;}String entryId=live?connection.activeMultihopEntryId():prefs().getString(MULTI_ENTRY,""),exitId=live?connection.activeMultihopExitId():prefs().getString(MULTI_EXIT,""),mode=live?connection.activeMultihopExitMode():prefs().getString(MULTI_MODE,"");try{AndroidNodeStore.Node entry=nodeById(entryId),exit=nodeById(exitId);if(entry==null||exit==null){multihopHint.setText(live?"Live graph identity unavailable":"Choose hops");return;}double a=telemetry.cachedMedian(entry.id),b=telemetry.cachedMedian(exit.id);StringBuilder s=new StringBuilder(live?"LIVE • ":"").append(entry.name);if(a>0)s.append(String.format(Locale.US," %.1f ms",a));s.append(" → ").append(exit.name);if(b>0)s.append(String.format(Locale.US," %.1f ms",b));if(currentPathMs>0&&live)s.append(String.format(Locale.US," • PATH %.1f ms",currentPathMs));s.append(" • ").append(mode);multihopHint.setText(s.toString());}catch(Exception error){multihopHint.setText(live?"Live graph identity unavailable":"Choose hops");}}
    private AndroidNodeStore.Node nodeById(String id)throws Exception{if(id==null||id.isEmpty())return null;for(AndroidNodeStore.Node n:nodeStore.list())if(n.id.equals(id))return n;return null;}

    private void showSettings(){JSONObject p=activeRouterProfile();if(p==null){toast("Select a Router VPN node first.");return;}AndroidProfileSettingsDialog.show(this,nodeStore,this::refreshAll);}
    private void setQuickKillSwitch(boolean enabled){if(mutationBusy()){toast("Disconnect/finish before changing persistent kill-switch policy.");refreshSettingsState();return;}try{JSONObject root=activeBundle(),p=selectedProfile(root);if(p==null)throw new IllegalStateException("Select a Router VPN node first.");p.put("kill_switch",enabled);p.put("kill_switch_policy",enabled?"on-connect":"off");nodeStore.importBundle(root.toString().getBytes(StandardCharsets.UTF_8));toast(enabled?"Kill switch enabled":"Kill switch disabled");}catch(Exception error){toast(safe(error));}refreshSettingsState();}
    private void refreshSettingsState(){JSONObject p=activeRouterProfile();boolean enabled=p!=null&&(!"off".equalsIgnoreCase(p.optString("kill_switch_policy","off"))||p.optBoolean("kill_switch",false));killSwitch.setChecked(enabled);if(autoRequirementsHint!=null){boolean encrypted=p!=null&&p.optBoolean("auto_require_encrypted",false),obfuscated=p!=null&&p.optBoolean("auto_require_obfuscation",false);String value=encrypted&&obfuscated?"Encrypted + Obfuscation":encrypted?"Encrypted":obfuscated?"Obfuscation":"Off";autoRequirementsHint.setText("AUTO requirements: "+value+" • Off by default • SMART never simplifies below enabled requirements");}}
    private void showMtuHelp(){new AlertDialog.Builder(this).setTitle("MTU").setMessage("Auto measured is the default. Fixed MTU applies until changed. Retest is specific to the selected node/mode/path and must use real loss/RTT/throughput evidence; Android does not invent a value when that tester is unavailable.").setPositiveButton("Open settings",(d,w)->showSettings()).setNeutralButton("Performance",(d,w)->showPerformance()).setNegativeButton("Close",null).show();}

    private void refreshForwardingState(){AndroidHomeStateStore.Snapshot home=AndroidHomeStateStore.snapshot(this);if(viaEntryProbe.isBusy()||!connection.isConnected()||"external".equals(home.logicalMode)){forwardingEnabled=null;forwardButton.setText("Forward");return;}if(forwardingBusy)return;forwardingBusy=true;forwardingMaster.get((enabled,error)->runOnUiThread(()->{forwardingBusy=false;if(error==null&&enabled!=null){forwardingEnabled=enabled;forwardButton.setText(enabled?"Forward ON":"Forward OFF");}else{forwardingEnabled=null;forwardButton.setText("Forward ?");}}));}
    private void showForwarding(){if(viaEntryProbe.isBusy()){dialog("Master port forwarding","Via-entry candidate measurement is using a temporary Router VPN tunnel. It will disconnect automatically; forwarding is not changed during this probe.");return;}AndroidHomeStateStore.Snapshot home=AndroidHomeStateStore.snapshot(this);if(!connection.isConnected()){dialog("Master port forwarding","Connect a Router VPN home-node path first. The forwarding master is a real server-owned policy and is not changed while disconnected.");return;}if("external".equals(home.logicalMode)){dialog("Master port forwarding","A direct external exit does not own your Router VPN home-node forwarding policy. Connect a Router VPN home-node path first.");return;}if(forwardingBusy){toast("Forwarding master state is already being verified.");return;}forwardingBusy=true;forwardButton.setText("Forward …");forwardingMaster.get((enabled,error)->runOnUiThread(()->{forwardingBusy=false;if(error!=null||enabled==null){forwardingEnabled=null;forwardButton.setText("Forward ?");dialog("Master port forwarding","Could not verify the real forwarding-master state: "+safe(error));return;}forwardingEnabled=enabled;forwardButton.setText(enabled?"Forward ON":"Forward OFF");String state=enabled?"ON":"OFF";new AlertDialog.Builder(this).setTitle("Master port forwarding • "+state).setMessage("This is the real server forwarding master on the active Router VPN home node. It gates WAN→tunnel forwarding rules and Protected DMZ. The request is authenticated through the active VPN path; the Setup Center admin token never leaves the server.").setPositiveButton(enabled?"Turn OFF":"Turn ON",(d,w)->setForwardingMaster(!enabled)).setNeutralButton("Rules in Setup Center",(d,w)->dialog("Forwarding rules","The master switch is controlled here. Individual persistent rules and Protected DMZ remain server-owned in Setup Center so targets/owners/reserved ports can be validated safely.")).setNegativeButton("Close",null).show();}));}
    private void setForwardingMaster(boolean enabled){if(forwardingBusy)return;forwardingBusy=true;forwardButton.setText("Forward …");forwardingMaster.set(enabled,(actual,error)->runOnUiThread(()->{forwardingBusy=false;if(error!=null||actual==null){forwardingEnabled=null;forwardButton.setText("Forward ?");dialog("Forwarding update failed",safe(error));return;}forwardingEnabled=actual;forwardButton.setText(actual?"Forward ON":"Forward OFF");toast("Server port-forwarding master is now "+(actual?"ON":"OFF")+".");}));}

    private void setQuickDns(String mode){if(mutationBusy()){toast("Disconnect/finish before changing DNS.");refreshDnsSelection();return;}try{JSONObject root=activeBundle(),p=selectedProfile(root);if(p==null)throw new IllegalStateException("Select a Router VPN node first.");if("fastest".equals(mode)&&p.optString("fastest_dns_host","").trim().isEmpty()){AndroidProductParity.showDNS(this,nodeStore);return;}p.put("dns_mode",mode);if("home".equals(mode)){p.put("dns_protocol","udp");p.put("dns_port",53);p.put("dns_host",p.optString("adguard_ipv4",p.optString("adguard_ipv6","")));}nodeStore.importBundle(root.toString().getBytes(StandardCharsets.UTF_8));toast("DNS set to "+mode+" for the next tunnel; runtime proof still required.");}catch(Exception error){toast(safe(error));}refreshDnsSelection();}
    private void refreshDnsSelection(){JSONObject p=activeRouterProfile();String mode=p==null?"home":p.optString("dns_mode","home").toLowerCase(Locale.US);String[]ids={"home","fastest","custom","dot","doh","doh3","rescue"};int index=0;for(int i=0;i<ids.length;i++)if(ids[i].equals(mode)){index=i;break;}dnsSpinner.setSelection(index,false);}

    private void showPairDialog(){
        if(mutationBusy()){toast("Disconnect/finish before adding or updating Router profiles.");return;}
        LinearLayout fields=new LinearLayout(this);fields.setOrientation(LinearLayout.VERTICAL);fields.setPadding(dp(20),dp(4),dp(20),0);
        EditText host=new EditText(this);host.setHint("AI Board LAN IP / hostname");host.setSingleLine(true);
        EditText code=new EditText(this);code.setHint("6-digit one-time pairing code");code.setSingleLine(true);code.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);
        fields.addView(host);fields.addView(code);
        AlertDialog pairDialog=new AlertDialog.Builder(this).setTitle("Add / update Router node").setMessage("Use the short-lived code from authenticated private Setup Center. Pairing stays LAN/private and one-time; the same stable node identity updates its stored profile.").setView(fields).setPositiveButton("Pair",null).setNegativeButton("Cancel",null).create();
        pairDialog.setOnShowListener(x->pairDialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
            if(mutationBusy()){toast("VPN state changed; disconnect/finish before redeeming the one-time pairing code.");return;}
            pairDialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);
            AndroidPairingClient.redeem(host.getText().toString(),code.getText().toString(),(bundle,error)->runOnUiThread(()->{
                if(error!=null){pairDialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);toast("Pairing failed: "+safe(error));return;}
                if(mutationBusy()){pairDialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);toast("VPN state changed after pairing redemption; bundle was not imported or selected. Disconnect, then pair again with a new code.");return;}
                try{AndroidNodeStore.Node node=nodeStore.importBundle(bundle);prefs().edit().putString(SELECTED_KIND,"router-vpn").putString(SELECTED_ID,node.id).apply();pairDialog.dismiss();refreshAll();toast("Added/updated and selected "+node.name);}catch(Exception importError){pairDialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);toast("Bundle rejected: "+safe(importError));}
            }));
        }));
        pairDialog.show();
    }

    private void openStandardExits(){if(mutationBusy()){toast("Disconnect/finish before adding, deleting, or selecting Custom / external exits.");return;}startActivity(new Intent(this,StandardExitActivity.class));}
    private void showHelp(){new AlertDialog.Builder(this).setTitle("Router VPN").setMessage("Map-first daily app: choose one Router or Custom node, or use ⚡ Fastest; Connect becomes Disconnect with live private-path RTT beside it. Multihop hop-2 candidates are measured through a real temporary proven hop-1 tunnel, then that probe tunnel is disconnected before selection. Live multihop map roles, path RTT and routed hop Mbps bind to the actual frozen runtime graph. Swipe up for Settings, Performance, Mode, DNS, Profiles and the real server forwarding master. Only real stored coordinates/measurements are rendered.").setPositiveButton("Run onboarding again",(d,w)->AndroidProductOnboarding.show(this,true)).setNeutralButton("Android VPN settings",(d,w)->startActivity(new Intent(Settings.ACTION_VPN_SETTINGS))).setNegativeButton("Close",null).show();}

    private JSONObject activeBundle()throws Exception{String active=nodeStore.activeId();if(active==null||active.isEmpty())throw new IllegalStateException("Select a Router VPN node first.");try(FileInputStream in=new FileInputStream(nodeStore.file(active));ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[]buf=new byte[8192];int n,total=0;while((n=in.read(buf))!=-1){total+=n;if(total>AndroidNodeStore.MAX_BUNDLE)throw new IllegalStateException("Bundle exceeds safety limit.");out.write(buf,0,n);}return new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8));}}
    private JSONObject activeRouterProfile(){try{return selectedProfile(activeBundle());}catch(Exception ignored){return null;}}
    private static JSONObject selectedProfile(JSONObject bundle){JSONArray a=bundle.optJSONArray("routerProfiles");String id=bundle.optString("selectedRouterID","");if(a==null)return null;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null&&id.equals(p.optString("id")))return p;}return a.length()>0?a.optJSONObject(0):null;}
    private List<String> allCatalogLayers()throws Exception{JSONObject root=activeBundle();JSONArray modes=root.optJSONArray("modes");Set<String>set=new LinkedHashSet<>();if(modes!=null)for(int i=0;i<modes.length();i++){JSONObject m=modes.optJSONObject(i);JSONArray l=m==null?null:m.optJSONArray("layers");if(l!=null)for(int j=0;j<l.length();j++){String v=l.optString(j,"").trim().toLowerCase(Locale.US);if(!v.isEmpty())set.add(v);}}return new ArrayList<>(set);}
    private List<CustomPreset> loadCustomPresets(){List<CustomPreset>out=new ArrayList<>();try{JSONArray a=new JSONArray(prefs().getString(CUSTOM_KEY,"[]"));for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;String name=p.optString("name","").trim();JSONArray l=p.optJSONArray("layers");List<String>layers=new ArrayList<>();if(l!=null)for(int j=0;j<l.length();j++){String v=l.optString(j,"").trim();if(!v.isEmpty())layers.add(v);}if(!name.isEmpty()&&!layers.isEmpty())out.add(new CustomPreset(name,layers));}}catch(Exception ignored){}return out;}
    private void saveCustomPreset(CustomPreset preset,String oldName){List<CustomPreset>all=loadCustomPresets();List<CustomPreset>next=new ArrayList<>();for(CustomPreset p:all)if((oldName==null||!p.name.equalsIgnoreCase(oldName))&&!p.name.equalsIgnoreCase(preset.name))next.add(p);next.add(preset);persistCustom(next);}
    private void deleteCustomPreset(String name){List<CustomPreset>next=new ArrayList<>();for(CustomPreset p:loadCustomPresets())if(!p.name.equalsIgnoreCase(name))next.add(p);persistCustom(next);}
    private void persistCustom(List<CustomPreset>values){JSONArray a=new JSONArray();for(CustomPreset p:values){JSONObject o=new JSONObject();try{o.put("name",p.name);o.put("layers",new JSONArray(p.layers));a.put(o);}catch(Exception ignored){}}prefs().edit().putString(CUSTOM_KEY,a.toString()).apply();}

    private void dialog(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
    private SharedPreferences prefs(){return getSharedPreferences(PREFS,MODE_PRIVATE);}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    private LinearLayout controlRow(String title){LinearLayout r=row();TextView label=text(title,13,true);label.setTextColor(Color.WHITE);label.setGravity(Gravity.END);r.addView(label,new LinearLayout.LayoutParams(dp(72),LinearLayout.LayoutParams.WRAP_CONTENT));return r;}
    private TextView text(String value,int sp,boolean bold){TextView v=new TextView(this);v.setText(value);v.setTextSize(sp);v.setTextColor(Color.WHITE);if(bold)v.setTypeface(v.getTypeface(),Typeface.BOLD);return v;}
    private Button primaryButton(String value){Button b=smallButton(value);b.setTextSize(17);b.setTypeface(b.getTypeface(),Typeface.BOLD);b.setTextColor(Color.WHITE);b.setBackgroundTintList(ColorStateList.valueOf(Color.rgb(95,78,220)));return b;}
    private Button smallButton(String value){Button b=new Button(this);b.setText(value);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(11);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(7),0,dp(7),0);b.setBackgroundTintList(ColorStateList.valueOf(Color.rgb(39,55,82)));return b;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(l,t,r,b);return p;}
    private int dp(float value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private static String safe(Throwable error){String value=error==null?"":error.getMessage();return value==null||value.trim().isEmpty()?"Router VPN error":value.trim();}
    private void toast(String message){Toast.makeText(this,message==null?"Router VPN":message,Toast.LENGTH_LONG).show();}
}
