#!/usr/bin/env bash
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo 'Run with sudo: sudo bash server/manage.sh'; exit 1; }
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# Terminal management must use the same generated exact-SHA compose contract as
# deliberate Portainer releases. The tracked portainer-current.yaml is only a
# reproducible template/baseline and must never be silently treated as latest.
if [[ -z ${ROUTER_VPN_PRODUCTION_COMPOSE:-} ]]; then
  cat >&2 <<'EOF'
ROUTER_VPN_PRODUCTION_COMPOSE is required.
Set it to the verified RouterVPN-Portainer-<release-sha>.yaml generated by the
GitHub Actions workflow "Exact-SHA production compose" for the release you
intend to install/upgrade. The tracked server/portainer-current.yaml baseline
is intentionally rejected as a current release.
EOF
  exit 2
fi
export ROUTER_VPN_PRODUCTION_COMPOSE

if [[ ! -s /opt/router-vpn/.env || ! -s /opt/router-vpn/.initialized ]]; then
  exec bash "$ROOT_DIR/server/install.sh"
fi
exec bash "$ROOT_DIR/server/upgrade.sh"
