#!/usr/bin/env bash
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo 'Run with sudo: sudo bash server/manage.sh'; exit 1; }
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# Terminal management must use the same generated exact-SHA compose contract as
# deliberate Portainer releases. The tracked portainer-current.yaml is only a
# reproducible template/baseline and must never be silently treated as latest.
if [[ -z ${ROUTER_VPN_PRODUCTION_COMPOSE:-} ]]; then
  cat >&2 <<'EOF'
ROUTER_VPN_PRODUCTION_COMPOSE is required.
Set it to the verified RouterVPN-Portainer-<release-sha>.yaml generated by the
GitHub Actions workflow "Exact-SHA production compose" for the release you
intend to install/upgrade. The tracked server/portainer-current.yaml baseline
is intentionally rejected as a current release.
EOF
  exit 2
fi
export ROUTER_VPN_PRODUCTION_COMPOSE

INSTALL_STATE="$ROOT_DIR/server/scripts/install-state.py"
command -v python3 >/dev/null 2>&1 || { echo 'Python 3 is required to classify Router VPN install state.' >&2; exit 1; }
state_rc=0
python3 "$INSTALL_STATE" /opt/router-vpn >/dev/null 2>&1 || state_rc=$?
case "$state_rc" in
  0) exec bash "$ROOT_DIR/server/upgrade.sh" ;;
  3) exec bash "$ROOT_DIR/server/install.sh" ;;
  *) echo 'Router VPN install state is partial, redirected, or unsafe; refusing to guess install versus upgrade.' >&2; exit "$state_rc" ;;
esac
