#!/usr/bin/env python3
"""Compile compatible combined client profiles from generated router credentials.

This does not pretend that every named protocol can be nested arbitrarily. It builds
single-TUN profiles that are valid with the engines already generated by this repo:

split: TCP -> VLESS/REALITY/Vision/uTLS, UDP -> Hysteria2/QUIC/TLS/Salamander
max:   TCP -> PQ VLESS/REALITY/Vision/uTLS through local Xray SOCKS,
       UDP -> Hysteria2/QUIC/TLS/Salamander
"""
from __future__ import annotations

import copy
import json
import pathlib
import sys


def load(path: pathlib.Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write(path: pathlib.Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    path.chmod(0o600)


def tagged_proxy(config: dict) -> dict:
    for outbound in config.get("outbounds", []):
        if isinstance(outbound, dict) and outbound.get("tag") == "proxy":
            return copy.deepcopy(outbound)
    raise RuntimeError("generated profile has no proxy outbound")


def tun_inbound(config: dict, name: str, mtu: int) -> dict:
    for inbound in config.get("inbounds", []):
        if isinstance(inbound, dict) and inbound.get("type") == "tun":
            result = copy.deepcopy(inbound)
            result["interface_name"] = name
            result["mtu"] = mtu
            return result
    raise RuntimeError("generated profile has no TUN inbound")


def base_config(tun: dict, dns: dict, tcp: dict, udp: dict) -> dict:
    tcp["tag"] = "tcp-stack"
    udp["tag"] = "udp-stack"
    return {
        "log": {"level": "warn"},
        "dns": copy.deepcopy(dns),
        "inbounds": [tun],
        "outbounds": [tcp, udp, {"type": "direct", "tag": "direct"}],
        "route": {
            "rules": [
                {"protocol": "dns", "action": "hijack-dns"},
                {"network": "tcp", "action": "route", "outbound": "tcp-stack"},
                {"network": "udp", "action": "route", "outbound": "udp-stack"},
            ],
            "auto_detect_interface": True,
            "final": "tcp-stack",
        },
    }


def manifest(name: str, pq: bool, tcp_layers: list[str], udp_layers: list[str]) -> dict:
    return {
        "name": name,
        "transport": "both",
        "post_quantum": pq,
        "shared_layers": [
            "single TUN interface",
            "IPv4 + IPv6 full tunnel",
            "home AdGuard DNS",
            "optional DAITA-like cover traffic",
            "optional local SOCKS5-only listener",
        ],
        "tcp_stack": tcp_layers,
        "udp_stack": udp_layers,
        "notes": [
            "TCP and UDP branches run simultaneously and are selected by protocol.",
            "Port forwarding remains available through WireGuard/AmneziaWG peer modes; proxy-only modes do not create an inbound tunnel peer.",
        ],
    }


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate-stack-profiles.py BASE")
    base = pathlib.Path(sys.argv[1])
    generated = base / "client-bundle" / "generated"

    reality_path = generated / "reality-vision" / "sing-box.json"
    hy2_path = generated / "hysteria2" / "sing-box.json"
    pq_xray_path = generated / "reality-pq-vision" / "xray.json"
    pq_wrapper_path = generated / "reality-pq-vision" / "sing-box.json"
    for path in (reality_path, hy2_path, pq_xray_path, pq_wrapper_path):
        if not path.is_file():
            raise RuntimeError(f"missing generated prerequisite: {path}")

    reality = load(reality_path)
    hy2 = load(hy2_path)
    pq_wrapper = load(pq_wrapper_path)
    hy2_outbound = tagged_proxy(hy2)

    split = base_config(
        tun_inbound(reality, "router-vpn-split", 1340),
        reality.get("dns", {}),
        tagged_proxy(reality),
        copy.deepcopy(hy2_outbound),
    )
    split_dir = generated / "split"
    write(split_dir / "sing-box.json", split)
    write(
        split_dir / "stack.json",
        manifest(
            "Dual Transport",
            False,
            ["VLESS", "REALITY", "XTLS Vision", "Chrome uTLS", "TCP"],
            ["Hysteria2", "QUIC", "TLS 1.3", "Salamander obfuscation", "UDP"],
        ),
    )

    max_tcp = {
        "type": "socks",
        "tag": "tcp-stack",
        "server": "127.0.0.1",
        "server_port": 1090,
        "version": "5",
    }
    max_config = base_config(
        tun_inbound(pq_wrapper, "router-vpn-max", 1280),
        pq_wrapper.get("dns", {}),
        max_tcp,
        copy.deepcopy(hy2_outbound),
    )
    max_dir = generated / "max"
    write(max_dir / "xray.json", load(pq_xray_path))
    write(max_dir / "sing-box.json", max_config)
    write(
        max_dir / "stack.json",
        manifest(
            "MAX Split",
            True,
            [
                "VLESS post-quantum payload encryption (ML-KEM when generated by Xray)",
                "REALITY",
                "XTLS Vision",
                "Chrome uTLS fingerprint",
                "TCP",
            ],
            ["Hysteria2", "QUIC", "TLS 1.3", "Salamander obfuscation", "UDP"],
        ),
    )

    catalog = {
        "generated_profiles": ["split", "max"],
        "optional_adapters": {
            "wg-pq": ["wg-quick", "rosenpass", "rosenpass.toml"],
            "awg2-pq": ["awg-quick", "rosenpass", "rosenpass.toml"],
            "ss-v2ray": ["sing-box or Shadowsocks", "v2ray-plugin", "valid TLS domain/certificate"],
            "reality-xhttp": ["Xray XHTTP profile", "FinalMask-compatible server profile"],
            "naive-h2": ["naive client/server", "valid HTTPS domain/certificate"],
            "naive-h3": ["HTTP/3-capable naive client/server", "valid HTTPS domain/certificate"],
            "wg-quic": ["GotaTun", "matching router profile"],
            "wg-ss-v2ray": ["WireGuard-over-Shadowsocks engine", "matching router profile"],
            "exact-daita": ["Maybenot-enabled GotaTun on both ends"],
        },
    }
    write(generated / "STACK-CATALOG.json", catalog)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
