#!/usr/bin/env bash
set -euo pipefail
BASE=${1:?base directory}
ENDPOINT=${2:?public IP or hostname}
ADGUARD4=${3:?AdGuard IPv4}
REALITY_PORT=${4:-443}
HY2_PORT=${5:-8443}
SS_PORT=${6:-8388}
REALITY_TARGET=${7:-www.microsoft.com:443}
SING_BOX_IMAGE=${SING_BOX_IMAGE:-ghcr.io/sagernet/sing-box:v1.13.12}
PRIVATE_WRITE=/src/server/scripts/atomic-private-write.py
PRIVATE_BATCH=/src/server/scripts/atomic-private-batch.py
umask 077

mkdir -p "$BASE/config/transports" \
  "$BASE/client-bundle/generated/hysteria2" \
  "$BASE/client-bundle/generated/shadowsocks"
# REALITY/Vision is generated by Xray in generate-xray-pq.sh. Remove any stale
# sing-box implementation on upgrade so TCP 443 has exactly one owner.
rm -rf "$BASE/client-bundle/generated/reality-vision"

sb(){
  if command -v sing-box >/dev/null 2>&1; then sing-box "$@"; else docker run --rm "$SING_BOX_IMAGE" "$@"; fi
}

PRESERVED=$(python3 /src/server/scripts/preserve-generated-state.py transports "$BASE" 2>/dev/null || true)
if [[ -n "$PRESERVED" ]]; then
  eval "$PRESERVED"
  echo 'Preserving existing Shadowsocks/Hysteria2 credentials for same-deployment upgrade.' >&2
else
  SS_KEY=$(openssl rand -base64 32 | tr -d '\n')
  HY2_PASSWORD=$(openssl rand -base64 24 | tr -d '\n=/+' | head -c 28)
fi

CERT_NAME=${ROUTER_VPN_TLS_NAME:-router-vpn.home}
CERT_PATH="$BASE/config/transports/cert.pem"
KEY_PATH="$BASE/config/transports/key.pem"
cert_ok=0
if [[ -f "$CERT_PATH" && ! -L "$CERT_PATH" && -f "$KEY_PATH" && ! -L "$KEY_PATH" ]] \
  && openssl x509 -in "$CERT_PATH" -noout >/dev/null 2>&1 \
  && openssl pkey -in "$KEY_PATH" -noout >/dev/null 2>&1 \
  && openssl x509 -in "$CERT_PATH" -noout -ext subjectAltName 2>/dev/null | grep -Fq "DNS:$CERT_NAME"; then
  cert_pub=$(openssl x509 -in "$CERT_PATH" -pubkey -noout 2>/dev/null | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}')
  key_pub=$(openssl pkey -in "$KEY_PATH" -pubout -outform DER 2>/dev/null | sha256sum | awk '{print $1}')
  if [[ -n "$cert_pub" && "$cert_pub" == "$key_pub" ]]; then
    cert_ok=1
  fi
fi
if (( cert_ok == 0 )); then
  SAN="DNS:$CERT_NAME"
  TLS_TMP=$(mktemp -d "$BASE/config/transports/.tls.XXXXXX")
  trap 'rm -rf "${TLS_TMP:-}" "${GEN_TMP:-}" "${CHECK_CONFIG:-}"' EXIT
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 825 \
    -subj "/CN=$CERT_NAME" -addext "subjectAltName=$SAN" \
    -keyout "$TLS_TMP/key.pem" -out "$TLS_TMP/cert.pem" >/dev/null 2>&1
  openssl x509 -in "$TLS_TMP/cert.pem" -noout -ext subjectAltName | grep -Fq "DNS:$CERT_NAME"
  cert_pub=$(openssl x509 -in "$TLS_TMP/cert.pem" -pubkey -noout | openssl pkey -pubin -outform DER | sha256sum | awk '{print $1}')
  key_pub=$(openssl pkey -in "$TLS_TMP/key.pem" -pubout -outform DER | sha256sum | awk '{print $1}')
  [[ -n "$cert_pub" && "$cert_pub" == "$key_pub" ]]
  python3 "$PRIVATE_BATCH" "$KEY_PATH=$TLS_TMP/key.pem" "$CERT_PATH=$TLS_TMP/cert.pem"
  rm -rf "$TLS_TMP"
  TLS_TMP=
else
  # Republish the preserved pair through the private batch helper so upgrades
  # also converge old broad permissions without a post-commit chmod edge.
  python3 "$PRIVATE_BATCH" "$KEY_PATH=$KEY_PATH" "$CERT_PATH=$CERT_PATH"
  echo 'Preserving existing valid Hysteria2 TLS certificate/private key.' >&2
fi
python3 "$PRIVATE_WRITE" "$BASE/client-bundle/generated/hysteria2/cert.pem" < "$CERT_PATH"

GEN_TMP=$(mktemp -d "$BASE/config/transports/.generate.XXXXXX")
trap 'rm -rf "${TLS_TMP:-}" "${GEN_TMP:-}" "${CHECK_CONFIG:-}"' EXIT
python3 - "$GEN_TMP" "$ENDPOINT" "$ADGUARD4" "$HY2_PORT" "$SS_PORT" "$SS_KEY" "$HY2_PASSWORD" "$CERT_NAME" <<'PY'
import json,pathlib,sys
(tmp,endpoint,dns,hp,sp,sskey,hy2pass,tls_name)=sys.argv[1:]
tmp=pathlib.Path(tmp); hp,sp=map(int,(hp,sp))
server={
 "log":{"level":"warn"},
 "inbounds":[
  {"type":"hysteria2","tag":"hy2-in","listen":"::","listen_port":hp,
   "obfs":{"type":"salamander","password":hy2pass},
   "users":[{"name":"router-vpn","password":hy2pass}],
   "ignore_client_bandwidth":True,
   "tls":{"enabled":True,"certificate_path":"/etc/sing-box/cert.pem","key_path":"/etc/sing-box/key.pem"},
   "masquerade":{"type":"string","status_code":404,"headers":{"content-type":"text/html"},"content":"<html><body>Not found</body></html>"}},
  {"type":"shadowsocks","tag":"ss-in","listen":"::","listen_port":sp,
   "method":"2022-blake3-aes-256-gcm","password":sskey}
 ],
 "outbounds":[{"type":"direct","tag":"direct"}],
 "route":{"final":"direct"}
}

def client(outbound,mtu):
 return {
  "log":{"level":"warn"},
  "dns":{"servers":[{"type":"udp","tag":"home-dns","server":dns,"server_port":53,"detour":"proxy"}],"final":"home-dns"},
  "inbounds":[{"type":"tun","tag":"tun-in","interface_name":"router-vpn","address":["172.19.0.1/30","fdfe:dcba:9876::1/126"],"mtu":mtu,"auto_route":True,"strict_route":True}],
  "outbounds":[outbound,{"type":"direct","tag":"direct"}],
  "route":{"rules":[{"protocol":"dns","action":"hijack-dns"}],"auto_detect_interface":True,"final":"proxy"}
 }

hy2={"type":"hysteria2","tag":"proxy","server":endpoint,"server_port":hp,"password":hy2pass,"obfs":{"type":"salamander","password":hy2pass},
 "tls":{"enabled":True,"server_name":tls_name,"certificate_path":"cert.pem"}}
ss={"type":"shadowsocks","tag":"proxy","server":endpoint,"server_port":sp,"method":"2022-blake3-aes-256-gcm","password":sskey}
values={
 "server.json":server,
 "hysteria2.json":client(hy2,1360),
 "shadowsocks.json":client(ss,1380),
 "generated-secrets.json":{"hysteria2_password":hy2pass,"shadowsocks_key":sskey},
}
for name,value in values.items():
 (tmp/name).write_text(json.dumps(value,indent=2)+"\n",encoding="utf-8")
PY
python3 "$PRIVATE_BATCH" \
  "$BASE/config/transports/server.json=$GEN_TMP/server.json" \
  "$BASE/client-bundle/generated/hysteria2/sing-box.json=$GEN_TMP/hysteria2.json" \
  "$BASE/client-bundle/generated/shadowsocks/sing-box.json=$GEN_TMP/shadowsocks.json" \
  "$BASE/config/transports/generated-secrets.json=$GEN_TMP/generated-secrets.json"
rm -rf "$GEN_TMP"
GEN_TMP=

# Production mounts the transport certificate/key at /etc/sing-box. During
# initialization those mounts do not exist yet, so validate a disposable staging
# copy whose TLS paths point at generated files. This file is not authoritative.
CHECK_CONFIG=$(mktemp "$BASE/config/transports/.server.check.XXXXXX.json")
python3 - "$BASE/config/transports/server.json" "$CHECK_CONFIG" "$CERT_PATH" "$KEY_PATH" <<'PY'
import json,sys
src,dst,cert,key=sys.argv[1:]
x=json.load(open(src))
for inbound in x.get("inbounds",[]):
    tls=inbound.get("tls") or {}
    if tls.get("enabled"):
        tls["certificate_path"]=cert
        tls["key_path"]=key
json.dump(x,open(dst,"w"),indent=2)
open(dst,"a").write("\n")
PY
sb check -D "$BASE/config/transports" -c "$CHECK_CONFIG" >/dev/null
rm -f "$CHECK_CONFIG"
CHECK_CONFIG=
sb check -D "$BASE/client-bundle/generated/hysteria2" -c "$BASE/client-bundle/generated/hysteria2/sing-box.json" >/dev/null
sb check -D "$BASE/client-bundle/generated/shadowsocks" -c "$BASE/client-bundle/generated/shadowsocks/sing-box.json" >/dev/null
trap - EXIT
