#!/usr/bin/env bash
set -euo pipefail
BASE=${1:?base directory}
ENDPOINT=${2:?public IP or hostname}
ADGUARD4=${3:?AdGuard IPv4}
REALITY_PORT=${4:-443}
HY2_PORT=${5:-8443}
SS_PORT=${6:-8388}
REALITY_TARGET=${7:-www.microsoft.com:443}
SING_BOX_IMAGE=${SING_BOX_IMAGE:-ghcr.io/sagernet/sing-box:v1.13.12}

mkdir -p "$BASE/config/transports" \
  "$BASE/client-bundle/generated/hysteria2" \
  "$BASE/client-bundle/generated/shadowsocks"
# REALITY/Vision is generated by Xray in generate-xray-pq.sh. Remove any stale
# sing-box implementation on upgrade so TCP 443 has exactly one owner.
rm -rf "$BASE/client-bundle/generated/reality-vision"

sb(){
  if command -v sing-box >/dev/null 2>&1; then sing-box "$@"; else docker run --rm "$SING_BOX_IMAGE" "$@"; fi
}

SS_KEY=$(openssl rand -base64 32 | tr -d '\n')
HY2_PASSWORD=$(openssl rand -base64 24 | tr -d '\n=/+' | head -c 28)

CERT_NAME=${ROUTER_VPN_TLS_NAME:-router-vpn.home}
SAN="DNS:$CERT_NAME"
openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 825 \
  -subj "/CN=$CERT_NAME" -addext "subjectAltName=$SAN" \
  -keyout "$BASE/config/transports/key.pem" -out "$BASE/config/transports/cert.pem" >/dev/null 2>&1
cp "$BASE/config/transports/cert.pem" "$BASE/client-bundle/generated/hysteria2/cert.pem"

python3 - "$BASE" "$ENDPOINT" "$ADGUARD4" "$HY2_PORT" "$SS_PORT" "$SS_KEY" "$HY2_PASSWORD" "$CERT_NAME" <<'PY'
import json,sys,os
(base,endpoint,dns,hp,sp,sskey,hy2pass,tls_name)=sys.argv[1:]
hp,sp=map(int,(hp,sp))
server={
 "log":{"level":"warn"},
 "inbounds":[
  {"type":"hysteria2","tag":"hy2-in","listen":"::","listen_port":hp,
   "obfs":{"type":"salamander","password":hy2pass},
   "users":[{"name":"router-vpn","password":hy2pass}],
   "ignore_client_bandwidth":True,
   "tls":{"enabled":True,"certificate_path":"/etc/sing-box/cert.pem","key_path":"/etc/sing-box/key.pem"},
   "masquerade":{"type":"string","status_code":404,"headers":{"content-type":"text/html"},"content":"<html><body>Not found</body></html>"}},
  {"type":"shadowsocks","tag":"ss-in","listen":"::","listen_port":sp,
   "method":"2022-blake3-aes-256-gcm","password":sskey}
 ],
 "outbounds":[{"type":"direct","tag":"direct"}],
 "route":{"final":"direct"}
}
os.makedirs(f"{base}/config/transports",exist_ok=True)
json.dump(server,open(f"{base}/config/transports/server.json","w"),indent=2); open(f"{base}/config/transports/server.json","a").write("\n")

def client(outbound,mtu):
 return {
  "log":{"level":"warn"},
  "dns":{"servers":[{"type":"udp","tag":"home-dns","server":dns,"server_port":53,"detour":"proxy"}],"final":"home-dns"},
  "inbounds":[{"type":"tun","tag":"tun-in","interface_name":"router-vpn","address":["172.19.0.1/30","fdfe:dcba:9876::1/126"],"mtu":mtu,"auto_route":True,"strict_route":True}],
  "outbounds":[outbound,{"type":"direct","tag":"direct"}],
  "route":{"rules":[{"protocol":"dns","action":"hijack-dns"}],"auto_detect_interface":True,"final":"proxy"}
 }

hy2={"type":"hysteria2","tag":"proxy","server":endpoint,"server_port":hp,"password":hy2pass,"obfs":{"type":"salamander","password":hy2pass},
 "tls":{"enabled":True,"server_name":tls_name,"certificate_path":"cert.pem"}}
ss={"type":"shadowsocks","tag":"proxy","server":endpoint,"server_port":sp,"method":"2022-blake3-aes-256-gcm","password":sskey}
for name,obj,mtu in (("hysteria2",hy2,1360),("shadowsocks",ss,1380)):
 path=f"{base}/client-bundle/generated/{name}/sing-box.json"
 json.dump(client(obj,mtu),open(path,"w"),indent=2); open(path,"a").write("\n")

secrets={"hysteria2_password":hy2pass,"shadowsocks_key":sskey}
json.dump(secrets,open(f"{base}/config/transports/generated-secrets.json","w"),indent=2); open(f"{base}/config/transports/generated-secrets.json","a").write("\n")
PY
chmod 600 "$BASE/config/transports/"* "$BASE/client-bundle/generated/hysteria2/cert.pem" "$BASE/client-bundle/generated/"*/sing-box.json

# Production mounts the transport certificate/key at /etc/sing-box. During
# initialization those mounts do not exist yet, so validate a temporary copy
# whose TLS paths point at the generated files without changing production paths.
CHECK_CONFIG="$BASE/config/transports/server.check.json"
python3 - "$BASE/config/transports/server.json" "$CHECK_CONFIG" "$BASE/config/transports/cert.pem" "$BASE/config/transports/key.pem" <<'PY'
import json,sys
src,dst,cert,key=sys.argv[1:]
x=json.load(open(src))
for inbound in x.get("inbounds",[]):
    tls=inbound.get("tls") or {}
    if tls.get("enabled"):
        tls["certificate_path"]=cert
        tls["key_path"]=key
json.dump(x,open(dst,"w"),indent=2)
open(dst,"a").write("\n")
PY
sb check -D "$BASE/config/transports" -c "$CHECK_CONFIG" >/dev/null
rm -f "$CHECK_CONFIG"
sb check -D "$BASE/client-bundle/generated/hysteria2" -c "$BASE/client-bundle/generated/hysteria2/sing-box.json" >/dev/null
sb check -D "$BASE/client-bundle/generated/shadowsocks" -c "$BASE/client-bundle/generated/shadowsocks/sing-box.json" >/dev/null
