package common

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func repoFile(t *testing.T, rel string) string { t.Helper(); b,err:=os.ReadFile(filepath.Join("..","..",rel));if err!=nil{t.Fatalf("read %s: %v",rel,err)};return string(b) }
func TestAndroidNativeWireGuardIsRealAndOtherModesStayGated(t *testing.T){gradle:=repoFile(t,"android/app/build.gradle");for _,required:=range []string{"com.wireguard.android:tunnel:1.0.20260102","coreLibraryDesugaring"}{if !strings.Contains(gradle,required){t.Fatalf("Android native dependency missing %q",required)}};props:=repoFile(t,"android/gradle.properties");if !strings.Contains(props,"android.useAndroidX=true"){t.Fatal("WireGuard AndroidX dependency requires android.useAndroidX=true")};controller:=repoFile(t,"android/app/src/main/java/com/eabusham/routervpn/NativeWireGuardController.java");for _,required:=range []string{"new GoBackend","backend.setState(this, State.UP, config)","backend.setState(this, State.DOWN, null)","Config.parse",`profiles.optJSONObject("wg")`,`wg.optString("wg.conf"`}{if !strings.Contains(controller,required){t.Fatalf("Android WireGuard runtime missing %q",required)}};activity:=repoFile(t,"android/app/src/main/java/com/eabusham/routervpn/MainActivity.java");for _,required:=range []string{"VpnService.prepare(this)","Tunnel.State.UP","does not fake a live all-mode VPN connection","AmneziaWG","automatic reconnect are still unavailable"}{if !strings.Contains(activity,required){t.Fatalf("Android capability boundary missing %q",required)}}}
func TestWindowsRawAndLayeredNativeRuntimeIsRealAndUnsupportedModesStayGated(t *testing.T){wg:=repoFile(t,"client/native-wireguard-windows.ps1");for _,required:=range []string{"WireGuard\\wireguard.exe","/installtunnelservice","/uninstalltunnelservice","WireGuardTunnel`$","Is-Administrator","HOMEVPN_PROFILE_ID","Unsafe WireGuard profile path","will not fake native readiness through WSL"}{if !strings.Contains(wg,required){t.Fatalf("Windows native WireGuard helper missing %q",required)}};if strings.Contains(wg,"wsl.exe"){t.Fatal("native Windows WireGuard helper must not implement its tunnel through WSL")};layered:=repoFile(t,"client/native-windows-mode.ps1");for _,required:=range []string{"sing-box.exe","xray.exe","hysteria2","shadowsocks","naive-h2","naive-h3","reality-vision","reality-pq-vision","split","max","Patch-SingBox","Get-SelectedProfile","fastest_dns_host","hijack-dns","HOMEVPN_JUMBO","9000","Write-Utf8NoBom","Native Windows TUN modes require an elevated Router VPN process"}{if !strings.Contains(layered,required){t.Fatalf("Windows native layered helper missing %q",required)}};setup:=repoFile(t,"client/Setup-Windows-Runtime.ps1");for _,required:=range []string{"1.13.12","26.7.11","SHA-256 mismatch","e93fc531134eb1beb4efa3c74990a24e48456098a31c03b60d5ddf17f223cf98","af801b62c4d41d248d3db8016d4c6e2a7ccfb7ed443e3738aeb6f9e062321512"}{if !strings.Contains(setup,required){t.Fatalf("Windows pinned runtime setup missing %q",required)}};catalog:=repoFile(t,"client/Prepare-Windows-Mode-Catalog-v2.ps1");for _,required:=range []string{"$mode.id -eq 'wg'","native-wireguard-windows.ps1","native-windows-mode.ps1","no native Windows adapter yet","Write-Utf8NoBom"}{if !strings.Contains(catalog,required){t.Fatalf("Windows catalog boundary missing %q",required)}};startup:=repoFile(t,"cmd/client/windows_runtime.go");if !strings.Contains(startup,"Prepare-Windows-Mode-Catalog-v2.ps1")||!strings.Contains(startup,"sing-box/Xray TUN adapter"){t.Fatal("installed Windows package does not prepare native runtime catalog")};portable:=repoFile(t,"cmd/portable-launcher/main.go");for _,required:=range []string{"nativeLayeredWindowsModes","native-wireguard-windows.ps1","native-windows-mode.ps1","no native Windows adapter yet"}{if !strings.Contains(portable,required){t.Fatalf("Portable Windows native catalog missing %q",required)}};for _,body:=range []string{strings.ToLower(layered),strings.ToLower(setup),strings.ToLower(catalog),strings.ToLower(startup),strings.ToLower(portable)}{if strings.Contains(body,"wsl.exe")||strings.Contains(body,"requires wsl2"){t.Fatal("current Windows path must not depend on WSL")}}}
func TestApplePacketTunnelRemainsFailClosedUntilRealEngineBridgeExists(t *testing.T){provider:=repoFile(t,"ios/RouterVPN/PacketTunnel/PacketTunnelProvider.swift");for _,required:=range []string{"Link AmneziaWGKit/Xray engine before signing this target.","completionHandler(error)"}{if !strings.Contains(provider,required){t.Fatalf("Apple fail-closed boundary missing %q",required)}};if strings.Contains(provider,"completionHandler(nil)"){t.Fatal("Apple Packet Tunnel claims success even though the real engine bridge is still unavailable")};project:=repoFile(t,"ios/RouterVPN/project.yml");for _,required:=range []string{"NSLocalNetworkUsageDescription","com.apple.networkextension.packet-tunnel"}{if !strings.Contains(project,required){t.Fatalf("Apple local-network/tunnel declaration missing %q",required)}}}
func TestRetiredWindowsCatalogV1AndCompatibilityRuntimeAreNotReferenced(t *testing.T){for _,rel:=range []string{"cmd/client/windows_runtime.go","cmd/portable-launcher/main.go","deploy/package-builds.sh","client/Setup-Windows-Runtime.ps1"}{body:=repoFile(t,rel);if strings.Contains(body,"Prepare-Windows-Mode-Catalog.ps1")&&!strings.Contains(body,"Prepare-Windows-Mode-Catalog-v2.ps1"){t.Fatalf("%s references retired Windows catalog v1",rel)};lower:=strings.ToLower(body);if strings.Contains(lower,"wsl.exe")||strings.Contains(lower,"requires wsl2"){t.Fatalf("%s still depends on WSL",rel)}}}
