#!/usr/bin/env python3
from pathlib import Path
import hashlib
import sys

SPECS = {
    'routervpn-gtk-product.c': ('ac5ce597abeb363a87e1f8ffcc6339774d1fc62a7d24702d7b4b941c5715aee9', [
        (242, 242, [], ['static gboolean routervpn_phase_busy(const char *phase) {\n', "    if (phase == NULL || phase[0] == '\\0') return FALSE;\n", '    char *lower = g_ascii_strdown(phase, -1);\n', '    gboolean busy = strstr(lower, "connecting") != NULL || strstr(lower, "starting") != NULL ||\n', '        strstr(lower, "checking") != NULL || strstr(lower, "trying") != NULL ||\n', '        strstr(lower, "proving") != NULL || strstr(lower, "reasserting") != NULL ||\n', '        strstr(lower, "disconnecting") != NULL || strstr(lower, "stopping") != NULL ||\n', '        strstr(lower, "switching") != NULL || strstr(lower, "reconnecting") != NULL;\n', '    g_free(lower);\n', '    return busy;\n', '}\n', '\n', 'static gboolean routervpn_phase_disconnecting(const char *phase) {\n', "    if (phase == NULL || phase[0] == '\\0') return FALSE;\n", '    char *lower = g_ascii_strdown(phase, -1);\n', '    gboolean stopping = strstr(lower, "disconnecting") != NULL || strstr(lower, "stopping") != NULL;\n', '    g_free(lower);\n', '    return stopping;\n', '}\n', '\n', 'static gboolean routervpn_mutation_busy_from_status(JsonObject *obj) {\n', '    if (obj == NULL) return TRUE;\n', '    gboolean connected = json_object_has_member(obj, "connected") && json_object_get_boolean_member(obj, "connected");\n', '    return connected || routervpn_phase_busy(obj_string(obj, "phase"));\n', '}\n', '\n', 'static gboolean routervpn_mutation_busy(App *app) {\n', '    (void)app;\n', '    Buffer out = {0}; char *err = NULL; gboolean busy = TRUE;\n', '    if (api_request("/api/status", "GET", NULL, 3500, &out, &err)) {\n', '        JsonNode *root = parse_json(out.data);\n', '        if (root != NULL && JSON_NODE_HOLDS_OBJECT(root)) busy = routervpn_mutation_busy_from_status(json_node_get_object(root));\n', '        if (root != NULL) json_node_free(root);\n', '    }\n', '    g_free(err); free(out.data);\n', '    return busy;\n', '}\n', '\n', 'static gboolean routervpn_require_mutation_idle(App *app, const char *action) {\n', '    if (!routervpn_mutation_busy(app)) return TRUE;\n', '    char *line = g_strdup_printf("Disconnect Router VPN or let the active transition finish before %s; live session identity and proof are immutable.", action != NULL ? action : "changing persistent session state");\n', '    append_diag(app, line);\n', '    gtk_label_set_text(GTK_LABEL(app->error), line);\n', '    g_free(line);\n', '    return FALSE;\n', '}\n', '\n']),
        (443, 445, ['    (void)button;\n', '    post_and_log((App *)data, "/api/auto", "{}", 150000, "AUTO");\n'], ['    (void)button; App *app = data;\n', '    if (!routervpn_require_mutation_idle(app, "starting AUTO")) return;\n', '    post_and_log(app, "/api/auto", "{}", 150000, "AUTO");\n']),
        (474, 474, [], ['    if (!routervpn_require_mutation_idle(app, "starting the selected mode")) return;\n']),
        (490, 490, [], ['    if (!routervpn_require_mutation_idle(app, "selecting another Router VPN node")) { refresh_profiles(app); return; }\n']),
    ]),
    'routervpn-gtk-product-v3.c': ('db2a0535627ef0d793db1c5731ff314d6be2827e28fe5bd359613b5eb6555e1e', [
        (69, 69, [], ['    if (!routervpn_require_mutation_idle(app, "opening node pairing")) return;\n']),
        (100, 100, [], ['        } else if (!routervpn_require_mutation_idle(app, "redeeming the one-time pairing code")) {\n', '            append_diag(app, "Pairing code was not consumed because VPN state changed while the dialog was open.");\n']),
        (124, 124, [], ['    if (!routervpn_require_mutation_idle(app, "importing a linked node")) return;\n']),
        (141, 141, [], ['        } else if (!routervpn_require_mutation_idle(app, "committing linked-node import")) {\n', '            append_diag(app, "Import cancelled because VPN state changed while the file picker was open.");\n']),
        (166, 166, [], ['    if (!routervpn_require_mutation_idle(app, "removing a linked node")) return;\n']),
        (178, 178, [], ['        if (!routervpn_require_mutation_idle(app, "committing linked-node removal")) { gtk_widget_destroy(dialog); return; }\n']),
    ]),
    'routervpn-gtk-product-v4.c': ('48190618125e0ca4cc3cfd70507149cb1a3a6d086167a2f2115f2b5f4d6517ab', [
        (83, 83, [], ['    if (!routervpn_require_mutation_idle(app, "selecting the lowest-latency node")) return;\n']),
        (109, 109, [], ['    } else if (!routervpn_require_mutation_idle(app, "committing the lowest-latency node selection")) {\n', '        append_diag(app, "Lowest-latency result discarded because VPN state changed during measurement.");\n']),
        (128, 128, [], ['    if (!routervpn_require_mutation_idle(app, "importing a Router or external node")) return;\n']),
        (145, 145, [], ['        } else if (!routervpn_require_mutation_idle(app, "committing Router or external node import")) {\n', '            append_diag(app, "Import cancelled because VPN state changed while the file picker was open.");\n']),
        (186, 186, [], ['    if (!routervpn_require_mutation_idle(app, "starting an external connection")) return;\n']),
        (214, 214, [], ['    if (!routervpn_require_mutation_idle(app, "starting an external via-entry connection")) return;\n']),
        (249, 249, [], ['        if (!routervpn_require_mutation_idle(app, "committing an external via-entry connection")) { gtk_widget_destroy(dialog); return; }\n']),
    ]),
    'routervpn-profile-settings-v1.inc': ('8aeaf190c5a2aaed30dbf66070687c23dac10cd40bace4fb024d96e84c0e832a', [
        (243, 243, [], ['    if (!routervpn_require_mutation_idle(state->app, "starting multihop")) { linux_multihop_update_summary_v7(state, "Disconnect Router VPN or let the active transition finish before changing the live route graph."); return; }\n']),
        (368, 368, [], ['    gboolean mutation_busy = routervpn_mutation_busy(app);\n']),
        (459, 459, [], ['    GtkWidget *save_button = gtk_dialog_get_widget_for_response(GTK_DIALOG(dialog), GTK_RESPONSE_OK);\n', '    GtkWidget *mutable_widgets[] = {multihop, lan, kill, ipv6, base, fallback, mtu, manual, daita, jumbo, socks, startup, autoconnect};\n', '    for (guint i = 0; i < G_N_ELEMENTS(mutable_widgets); i++) gtk_widget_set_sensitive(mutable_widgets[i], !mutation_busy);\n', '    if (save_button != NULL) gtk_widget_set_sensitive(save_button, !mutation_busy);\n', '    if (mutation_busy) gtk_label_set_text(GTK_LABEL(note), "Connected/transitioning: settings are read-only. Disconnect Router VPN or let the active transition finish before saving persistent node policy.");\n', '\n']),
        (464, 464, [], ['        if (!routervpn_require_mutation_idle(app, "saving persistent node settings")) { gtk_widget_destroy(dialog); json_node_free(root); g_free(err); free(out.data); refresh_home_summary_v6(app); return; }\n']),
    ]),
    'routervpn-unified-shell-v8.inc': ('b2d82155dce50cca68d74cd51a55c527f67438b2a21f871be945ea092f5c5a9e', [
        (135, 135, [], ['    if (!routervpn_require_mutation_idle(state->app, "editing CUSTOM presets")) { linux_unified_refresh_mode_combo_v8(state); return; }\n']),
        (151, 151, [], ['        if (!routervpn_require_mutation_idle(state->app, "deleting a CUSTOM preset")) { gtk_widget_destroy(dialog); g_ptr_array_unref(checks); g_hash_table_unref(old); g_free(editing); g_free(old_layers); linux_unified_refresh_mode_combo_v8(state); return; }\n']),
        (153, 153, [], ['        if (!routervpn_require_mutation_idle(state->app, "saving a CUSTOM preset")) { gtk_widget_destroy(dialog); g_ptr_array_unref(checks); g_hash_table_unref(old); g_free(editing); g_free(old_layers); linux_unified_refresh_mode_combo_v8(state); return; }\n']),
        (163, 163, [], ['    if (!routervpn_require_mutation_idle(state->app, "changing the selected mode")) { linux_unified_refresh_mode_combo_v8(state); return; }\n']),
        (174, 176, ['    (void)button; LinuxUnifiedV8 *state=data; Buffer out={0};char *err=NULL;gboolean active=FALSE;\n', '    if(api_request("/api/status","GET",NULL,4000,&out,&err)){JsonNode *root=parse_json(out.data);if(root!=NULL&&JSON_NODE_HOLDS_OBJECT(root)){JsonObject *obj=json_node_get_object(root);gboolean connected=json_object_has_member(obj,"connected")&&json_object_get_boolean_member(obj,"connected");const char *phase=obj_string(obj,"phase");active=connected||g_str_has_prefix(phase,"starting")||g_str_has_prefix(phase,"checking")||strstr(phase,"trying")!=NULL||strstr(phase,"proving")!=NULL;json_node_free(root);}}g_free(err);free(out.data);\n'], ['    (void)button; LinuxUnifiedV8 *state=data; Buffer out={0}; char *err=NULL; gboolean status_ok=FALSE, active=FALSE, disconnecting=FALSE;\n', '    if(api_request("/api/status","GET",NULL,4000,&out,&err)){JsonNode *root=parse_json(out.data);if(root!=NULL&&JSON_NODE_HOLDS_OBJECT(root)){JsonObject *obj=json_node_get_object(root);const char *phase=obj_string(obj,"phase");status_ok=TRUE;active=routervpn_mutation_busy_from_status(obj);disconnecting=routervpn_phase_disconnecting(phase);json_node_free(root);}}g_free(err);free(out.data);\n', '    if(!status_ok){append_diag(state->app,"Status unavailable; refusing to change the live session.");return;}\n', '    if(disconnecting){append_diag(state->app,"Disconnect already in progress.");return;}\n']),
        (177, 177, [], ['    if(!routervpn_require_mutation_idle(state->app,"starting a new connection"))return;\n']),
        (178, 179, ['    char *external_id=NULL;if(linux_unified_selected_external_v8(&external_id)){char *body=json_string_body("profile_id",external_id);post_and_log(state->app,"/api/external-profile/connect",body,180000,"Custom/external exit");g_free(body);g_free(external_id);return;}g_free(external_id);\n'], ['    char *external_id=NULL;if(linux_unified_selected_external_v8(&external_id)){if(!routervpn_require_mutation_idle(state->app,"starting a Custom/external exit")){g_free(external_id);return;}char *body=json_string_body("profile_id",external_id);post_and_log(state->app,"/api/external-profile/connect",body,180000,"Custom/external exit");g_free(body);g_free(external_id);return;}g_free(external_id);\n']),
        (180, 180, [], ['    if(!routervpn_require_mutation_idle(state->app,"starting the selected mode"))return;\n']),
        (186, 187, ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;const char *policy=gtk_toggle_button_get_active(toggle)?"on-connect":"off";char *body=g_strdup_printf("{\\"kill_switch_policy\\":\\"%s\\"}",policy);post_and_log(state->app,"/api/profile/settings",body,12000,"Kill switch");g_free(body);\n'], ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;if(!routervpn_require_mutation_idle(state->app,"changing persistent kill-switch policy")){linux_unified_refresh_v8(state);return;}const char *policy=gtk_toggle_button_get_active(toggle)?"on-connect":"off";char *body=g_strdup_printf("{\\"kill_switch_policy\\":\\"%s\\"}",policy);post_and_log(state->app,"/api/profile/settings",body,12000,"Kill switch");g_free(body);\n']),
        (189, 190, ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;const char *mode=gtk_combo_box_get_active_id(combo);if(mode==NULL)return;if(strcmp(mode,"custom")==0||strcmp(mode,"dot")==0||strcmp(mode,"doh")==0||strcmp(mode,"doh3")==0){linux_unified_show_detail_v8(state,3);return;}char *body=g_strdup_printf("{\\"mode\\":\\"%s\\"}",mode);post_and_log(state->app,"/api/dns/policy",body,12000,"DNS policy");g_free(body);\n'], ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;if(!routervpn_require_mutation_idle(state->app,"changing DNS policy")){linux_unified_refresh_v8(state);return;}const char *mode=gtk_combo_box_get_active_id(combo);if(mode==NULL)return;if(strcmp(mode,"custom")==0||strcmp(mode,"dot")==0||strcmp(mode,"doh")==0||strcmp(mode,"doh3")==0){linux_unified_show_detail_v8(state,3);return;}char *body=g_strdup_printf("{\\"mode\\":\\"%s\\"}",mode);post_and_log(state->app,"/api/dns/policy",body,12000,"DNS policy");g_free(body);\n']),
        (192, 193, ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;const char *id=gtk_combo_box_get_active_id(combo);if(id==NULL||id[0]==\'\\0\')return;char *body=json_string_body("id",id);post_and_log(state->app,"/api/profile/select",body,12000,"Node selection");g_free(body);refresh_all(state->app);\n'], ['    LinuxUnifiedV8 *state=data;if(state==NULL||state->syncing)return;if(!routervpn_require_mutation_idle(state->app,"selecting another Router VPN node")){linux_unified_refresh_v8(state);return;}const char *id=gtk_combo_box_get_active_id(combo);if(id==NULL||id[0]==\'\\0\')return;char *body=json_string_body("id",id);post_and_log(state->app,"/api/profile/select",body,12000,"Node selection");g_free(body);refresh_all(state->app);\n']),
        (196, 197, ['    Buffer out={0};char *err=NULL;if(api_request("/api/status","GET",NULL,3500,&out,&err)){JsonNode *root=parse_json(out.data);if(root!=NULL&&JSON_NODE_HOLDS_OBJECT(root)){JsonObject *obj=json_node_get_object(root);gboolean connected=json_object_has_member(obj,"connected")&&json_object_get_boolean_member(obj,"connected");const char *phase=obj_string(obj,"phase");gboolean transition=g_str_has_prefix(phase,"starting")||g_str_has_prefix(phase,"checking")||strstr(phase,"trying")!=NULL||strstr(phase,"proving")!=NULL;gtk_button_set_label(GTK_BUTTON(state->connect),(connected||transition)?"Disconnect":"Connect");char *text=g_strdup_printf("%s • logical %s • runtime %s • base %s",phase[0]?phase:"disconnected",obj_string(obj,"logical_mode"),obj_string(obj,"runtime_mode"),obj_string(obj,"base"));gtk_label_set_text(GTK_LABEL(state->status),text);g_free(text);json_node_free(root);}}g_free(err);free(out.data);\n'], ['    gboolean status_ok=FALSE,busy=TRUE,disconnecting=FALSE;Buffer out={0};char *err=NULL;if(api_request("/api/status","GET",NULL,3500,&out,&err)){JsonNode *root=parse_json(out.data);if(root!=NULL&&JSON_NODE_HOLDS_OBJECT(root)){JsonObject *obj=json_node_get_object(root);const char *phase=obj_string(obj,"phase");status_ok=TRUE;busy=routervpn_mutation_busy_from_status(obj);disconnecting=routervpn_phase_disconnecting(phase);gtk_button_set_label(GTK_BUTTON(state->connect),disconnecting?"Disconnecting…":busy?"Disconnect":"Connect");char *text=g_strdup_printf("%s • logical %s • runtime %s • base %s",phase[0]?phase:"disconnected",obj_string(obj,"logical_mode"),obj_string(obj,"runtime_mode"),obj_string(obj,"base"));gtk_label_set_text(GTK_LABEL(state->status),text);g_free(text);json_node_free(root);}}g_free(err);free(out.data);if(!status_ok){gtk_button_set_label(GTK_BUTTON(state->connect),"Checking…");gtk_label_set_text(GTK_LABEL(state->status),"Controller/status unavailable • session mutation locked");busy=TRUE;}gtk_widget_set_sensitive(state->connect,status_ok&&!disconnecting);gtk_widget_set_sensitive(state->node,!busy);gtk_widget_set_sensitive(state->kill_switch,!busy);gtk_widget_set_sensitive(state->multihop,!busy);gtk_widget_set_sensitive(state->mode,!busy);gtk_widget_set_sensitive(state->dns,!busy);\n']),
    ]),
}

def apply(src: Path, dst: Path):
    raw = src.read_text(encoding="utf-8")
    expected, changes = SPECS[src.name]
    actual = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    if actual != expected:
        raise SystemExit(f"Linux session mutation baseline drifted for {src.name}: {actual} != {expected}")
    lines = raw.splitlines(keepends=True)
    for i1, i2, old, new in reversed(changes):
        if lines[i1:i2] != old:
            raise SystemExit(f"Linux session mutation line anchor drifted for {src.name}:{i1}:{i2}")
        lines[i1:i2] = new
    dst.write_text("".join(lines), encoding="utf-8")

def main():
    if len(sys.argv) < 3 or (len(sys.argv)-1) % 2:
        raise SystemExit("usage: apply-session-mutation.py SRC DST [SRC DST ...]")
    for i in range(1, len(sys.argv), 2):
        src, dst = Path(sys.argv[i]), Path(sys.argv[i+1])
        if src.name not in SPECS:
            raise SystemExit(f"unsupported Linux session mutation source: {src.name}")
        apply(src, dst)

if __name__ == "__main__": main()
